<template>
  <AppLayout>
    <div class="space-y-6 p-6">
      <div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">推广管理</h1><p class="mt-1 text-sm text-gray-500">推广成员、可配置渠道和拉新效果统一统计。链接使用 <code>?source=渠道编码</code>。</p></div><div class="flex gap-2"><input v-model="start" type="date" class="input"><input v-model="end" type="date" class="input"><button class="btn btn-secondary" @click="load">刷新</button></div></div>
      <section class="card overflow-hidden"><div class="border-b border-gray-200 p-5 dark:border-dark-700"><h2 class="font-semibold">渠道报表</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-gray-200 text-xs text-gray-500"><tr><th class="px-4 py-3">渠道</th><th class="px-4 py-3">类型</th><th class="px-4 py-3">负责人</th><th class="px-4 py-3">注册</th><th class="px-4 py-3">付费用户</th><th class="px-4 py-3">充值</th><th class="px-4 py-3">消耗收入</th><th class="px-4 py-3">利润</th><th class="px-4 py-3">CAC</th><th class="px-4 py-3">ROI</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="row in report?.rows" :key="row.channel_id"><td class="px-4 py-3"><b>{{ row.name }}</b><div class="text-xs text-gray-500">{{ row.code }}</div></td><td class="px-4 py-3">{{ row.channel_type }}</td><td class="px-4 py-3">{{ row.promoter_name || '—' }}</td><td class="px-4 py-3">{{ row.new_users }}</td><td class="px-4 py-3">{{ row.paying_users }}</td><td class="px-4 py-3">{{ money(row.recharge) }}</td><td class="px-4 py-3">{{ money(row.revenue) }}</td><td class="px-4 py-3">{{ money(row.profit) }}</td><td class="px-4 py-3">{{ money(row.cac) }}</td><td class="px-4 py-3">{{ row.roi ? `${(row.roi * 100).toFixed(2)}%` : '—' }}</td></tr><tr v-if="!report?.rows.length"><td colspan="10" class="px-4 py-10 text-center text-gray-500">暂无渠道数据</td></tr></tbody></table></div></section>
      <section class="grid gap-6 xl:grid-cols-2"><div class="card p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold">推广成员</h2><button class="btn btn-primary btn-sm" @click="newPromoter">新增</button></div><div class="space-y-2"><div v-for="item in promoters" :key="item.id" class="flex items-center justify-between border-b border-gray-100 py-3 dark:border-dark-700"><div><b>{{ item.name }}</b><div class="text-xs text-gray-500">{{ item.contact }} · 提成 {{ item.commission_rate }}%</div></div><button class="btn btn-secondary btn-sm" @click="editPromoter(item)">编辑</button></div></div></div><div class="card p-5"><div class="mb-4 flex items-center justify-between"><h2 class="font-semibold">推广渠道</h2><button class="btn btn-primary btn-sm" @click="newChannel">新增</button></div><div class="space-y-2"><div v-for="item in channels" :key="item.id" class="flex items-center justify-between border-b border-gray-100 py-3 dark:border-dark-700"><div><b>{{ item.name }}</b><div class="text-xs text-gray-500">{{ item.code }} · {{ item.channel_type }} · {{ item.promoter_name || '未分配' }}</div></div><button class="btn btn-secondary btn-sm" @click="editChannel(item)">编辑</button></div></div></div></section>
      <div v-if="modal" class="card p-5"><h2 class="mb-4 font-semibold">{{ modal.kind === 'promoter' ? '推广成员' : '推广渠道' }}</h2><form class="grid gap-4 md:grid-cols-2" @submit.prevent="save"><label class="field"><span>名称</span><input v-model="form.name" class="input" required></label><label class="field"><span>{{ modal.kind === 'promoter' ? '联系方式' : '渠道编码' }}</span><input v-model="form.second" class="input" required></label><label v-if="modal.kind === 'channel'" class="field"><span>渠道类型</span><input v-model="form.channel_type" class="input" placeholder="SEO / 论坛 / TG群 / 自定义"></label><label v-else class="field"><span>提成比例</span><input v-model.number="form.commission_rate" class="input" type="number" min="0" max="100" step="0.01"></label><label class="field md:col-span-2"><span>备注</span><input v-model="form.notes" class="input"></label><div class="flex justify-end gap-2 md:col-span-2"><button type="button" class="btn btn-secondary" @click="modal=null">取消</button><button class="btn btn-primary">保存</button></div></form></div>
    </div>
  </AppLayout>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import promotionAPI, { type PromotionChannel, type PromotionPromoter, type PromotionReport } from '@/api/admin/promotion'
const promoters=ref<PromotionPromoter[]>([]), channels=ref<PromotionChannel[]>([]), report=ref<PromotionReport|null>(null)
const end=ref(new Date().toISOString().slice(0,10)); const d=new Date(); d.setDate(d.getDate()-30); const start=ref(d.toISOString().slice(0,10))
const modal=ref<{kind:'promoter'|'channel';item?:PromotionPromoter|PromotionChannel}|null>(null); const form=reactive<any>({name:'',second:'',channel_type:'other',commission_rate:0,notes:''})
function money(v:number){return (v||0).toFixed(4)}
function reset(){Object.assign(form,{name:'',second:'',channel_type:'other',commission_rate:0,notes:''})}
function newPromoter(){reset();modal.value={kind:'promoter'}} function newChannel(){reset();modal.value={kind:'channel'}}
function editPromoter(x:PromotionPromoter){reset();Object.assign(form,{name:x.name,second:x.contact,commission_rate:x.commission_rate,notes:x.notes});modal.value={kind:'promoter',item:x}}
function editChannel(x:PromotionChannel){reset();Object.assign(form,{name:x.name,second:x.code,channel_type:x.channel_type,notes:x.notes});modal.value={kind:'channel',item:x}}
async function load(){const p={start_time:new Date(`${start.value}T00:00:00`).toISOString(),end_time:new Date(`${end.value}T23:59:59.999`).toISOString()};const [a,b,c]=await Promise.all([promotionAPI.listPromoters(),promotionAPI.listChannels(),promotionAPI.report(p)]);promoters.value=a.data;channels.value=b.data;report.value=c.data}
async function save(){if(!modal.value)return;const m=modal.value;if(m.kind==='promoter'){const x={name:form.name,contact:form.second,commission_rate:Number(form.commission_rate)||0,enabled:true,notes:form.notes};m.item?await promotionAPI.updatePromoter(m.item.id,x):await promotionAPI.createPromoter(x)}else{const x={name:form.name,code:form.second,channel_type:form.channel_type||'other',enabled:true,notes:form.notes,promoter_id:null};m.item?await promotionAPI.updateChannel(m.item.id,x):await promotionAPI.createChannel(x)}modal.value=null;await load()}
onMounted(load)
</script>
