// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeyreputation"
)

// APIKeyReputationCreate is the builder for creating a APIKeyReputation entity.
type APIKeyReputationCreate struct {
	config
	mutation *APIKeyReputationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyReputationCreate) SetAPIKeyID(v int64) *APIKeyReputationCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *APIKeyReputationCreate) SetScore(v int) *APIKeyReputationCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableScore(v *int) *APIKeyReputationCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetSevereHits sets the "severe_hits" field.
func (_c *APIKeyReputationCreate) SetSevereHits(v int) *APIKeyReputationCreate {
	_c.mutation.SetSevereHits(v)
	return _c
}

// SetNillableSevereHits sets the "severe_hits" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableSevereHits(v *int) *APIKeyReputationCreate {
	if v != nil {
		_c.SetSevereHits(*v)
	}
	return _c
}

// SetTotalHits sets the "total_hits" field.
func (_c *APIKeyReputationCreate) SetTotalHits(v int) *APIKeyReputationCreate {
	_c.mutation.SetTotalHits(v)
	return _c
}

// SetNillableTotalHits sets the "total_hits" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableTotalHits(v *int) *APIKeyReputationCreate {
	if v != nil {
		_c.SetTotalHits(*v)
	}
	return _c
}

// SetLastEventAt sets the "last_event_at" field.
func (_c *APIKeyReputationCreate) SetLastEventAt(v time.Time) *APIKeyReputationCreate {
	_c.mutation.SetLastEventAt(v)
	return _c
}

// SetNillableLastEventAt sets the "last_event_at" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableLastEventAt(v *time.Time) *APIKeyReputationCreate {
	if v != nil {
		_c.SetLastEventAt(*v)
	}
	return _c
}

// SetScoredAt sets the "scored_at" field.
func (_c *APIKeyReputationCreate) SetScoredAt(v time.Time) *APIKeyReputationCreate {
	_c.mutation.SetScoredAt(v)
	return _c
}

// SetNillableScoredAt sets the "scored_at" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableScoredAt(v *time.Time) *APIKeyReputationCreate {
	if v != nil {
		_c.SetScoredAt(*v)
	}
	return _c
}

// SetSanction sets the "sanction" field.
func (_c *APIKeyReputationCreate) SetSanction(v string) *APIKeyReputationCreate {
	_c.mutation.SetSanction(v)
	return _c
}

// SetNillableSanction sets the "sanction" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableSanction(v *string) *APIKeyReputationCreate {
	if v != nil {
		_c.SetSanction(*v)
	}
	return _c
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (_c *APIKeyReputationCreate) SetSanctionedAt(v time.Time) *APIKeyReputationCreate {
	_c.mutation.SetSanctionedAt(v)
	return _c
}

// SetNillableSanctionedAt sets the "sanctioned_at" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableSanctionedAt(v *time.Time) *APIKeyReputationCreate {
	if v != nil {
		_c.SetSanctionedAt(*v)
	}
	return _c
}

// SetSanctionReason sets the "sanction_reason" field.
func (_c *APIKeyReputationCreate) SetSanctionReason(v string) *APIKeyReputationCreate {
	_c.mutation.SetSanctionReason(v)
	return _c
}

// SetNillableSanctionReason sets the "sanction_reason" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableSanctionReason(v *string) *APIKeyReputationCreate {
	if v != nil {
		_c.SetSanctionReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyReputationCreate) SetCreatedAt(v time.Time) *APIKeyReputationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableCreatedAt(v *time.Time) *APIKeyReputationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyReputationCreate) SetUpdatedAt(v time.Time) *APIKeyReputationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyReputationCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyReputationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the APIKeyReputationMutation object of the builder.
func (_c *APIKeyReputationCreate) Mutation() *APIKeyReputationMutation {
	return _c.mutation
}

// Save creates the APIKeyReputation in the database.
func (_c *APIKeyReputationCreate) Save(ctx context.Context) (*APIKeyReputation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyReputationCreate) SaveX(ctx context.Context) *APIKeyReputation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyReputationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyReputationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyReputationCreate) defaults() {
	if _, ok := _c.mutation.Score(); !ok {
		v := apikeyreputation.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.SevereHits(); !ok {
		v := apikeyreputation.DefaultSevereHits
		_c.mutation.SetSevereHits(v)
	}
	if _, ok := _c.mutation.TotalHits(); !ok {
		v := apikeyreputation.DefaultTotalHits
		_c.mutation.SetTotalHits(v)
	}
	if _, ok := _c.mutation.ScoredAt(); !ok {
		v := apikeyreputation.DefaultScoredAt()
		_c.mutation.SetScoredAt(v)
	}
	if _, ok := _c.mutation.Sanction(); !ok {
		v := apikeyreputation.DefaultSanction
		_c.mutation.SetSanction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeyreputation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeyreputation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyReputationCreate) check() error {
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyReputation.api_key_id"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "APIKeyReputation.score"`)}
	}
	if _, ok := _c.mutation.SevereHits(); !ok {
		return &ValidationError{Name: "severe_hits", err: errors.New(`ent: missing required field "APIKeyReputation.severe_hits"`)}
	}
	if _, ok := _c.mutation.TotalHits(); !ok {
		return &ValidationError{Name: "total_hits", err: errors.New(`ent: missing required field "APIKeyReputation.total_hits"`)}
	}
	if _, ok := _c.mutation.ScoredAt(); !ok {
		return &ValidationError{Name: "scored_at", err: errors.New(`ent: missing required field "APIKeyReputation.scored_at"`)}
	}
	if _, ok := _c.mutation.Sanction(); !ok {
		return &ValidationError{Name: "sanction", err: errors.New(`ent: missing required field "APIKeyReputation.sanction"`)}
	}
	if v, ok := _c.mutation.Sanction(); ok {
		if err := apikeyreputation.SanctionValidator(v); err != nil {
			return &ValidationError{Name: "sanction", err: fmt.Errorf(`ent: validator failed for field "APIKeyReputation.sanction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyReputation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyReputation.updated_at"`)}
	}
	return nil
}

func (_c *APIKeyReputationCreate) sqlSave(ctx context.Context) (*APIKeyReputation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyReputationCreate) createSpec() (*APIKeyReputation, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyReputation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeyreputation.Table, sqlgraph.NewFieldSpec(apikeyreputation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(apikeyreputation.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(apikeyreputation.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.SevereHits(); ok {
		_spec.SetField(apikeyreputation.FieldSevereHits, field.TypeInt, value)
		_node.SevereHits = value
	}
	if value, ok := _c.mutation.TotalHits(); ok {
		_spec.SetField(apikeyreputation.FieldTotalHits, field.TypeInt, value)
		_node.TotalHits = value
	}
	if value, ok := _c.mutation.LastEventAt(); ok {
		_spec.SetField(apikeyreputation.FieldLastEventAt, field.TypeTime, value)
		_node.LastEventAt = &value
	}
	if value, ok := _c.mutation.ScoredAt(); ok {
		_spec.SetField(apikeyreputation.FieldScoredAt, field.TypeTime, value)
		_node.ScoredAt = value
	}
	if value, ok := _c.mutation.Sanction(); ok {
		_spec.SetField(apikeyreputation.FieldSanction, field.TypeString, value)
		_node.Sanction = value
	}
	if value, ok := _c.mutation.SanctionedAt(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionedAt, field.TypeTime, value)
		_node.SanctionedAt = &value
	}
	if value, ok := _c.mutation.SanctionReason(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionReason, field.TypeString, value)
		_node.SanctionReason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeyreputation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyreputation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyReputation.Create().
//		SetAPIKeyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyReputationUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyReputationCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyReputationUpsertOne {
	_c.conflict = opts
	return &APIKeyReputationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyReputationCreate) OnConflictColumns(columns ...string) *APIKeyReputationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyReputationUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyReputationUpsertOne is the builder for "upsert"-ing
	//  one APIKeyReputation node.
	APIKeyReputationUpsertOne struct {
		create *APIKeyReputationCreate
	}

	// APIKeyReputationUpsert is the "OnConflict" setter.
	APIKeyReputationUpsert struct {
		*sql.UpdateSet
	}
)

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyReputationUpsert) SetAPIKeyID(v int64) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateAPIKeyID() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeyReputationUpsert) AddAPIKeyID(v int64) *APIKeyReputationUpsert {
	u.Add(apikeyreputation.FieldAPIKeyID, v)
	return u
}

// SetScore sets the "score" field.
func (u *APIKeyReputationUpsert) SetScore(v int) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateScore() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *APIKeyReputationUpsert) AddScore(v int) *APIKeyReputationUpsert {
	u.Add(apikeyreputation.FieldScore, v)
	return u
}

// SetSevereHits sets the "severe_hits" field.
func (u *APIKeyReputationUpsert) SetSevereHits(v int) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldSevereHits, v)
	return u
}

// UpdateSevereHits sets the "severe_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateSevereHits() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldSevereHits)
	return u
}

// AddSevereHits adds v to the "severe_hits" field.
func (u *APIKeyReputationUpsert) AddSevereHits(v int) *APIKeyReputationUpsert {
	u.Add(apikeyreputation.FieldSevereHits, v)
	return u
}

// SetTotalHits sets the "total_hits" field.
func (u *APIKeyReputationUpsert) SetTotalHits(v int) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldTotalHits, v)
	return u
}

// UpdateTotalHits sets the "total_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateTotalHits() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldTotalHits)
	return u
}

// AddTotalHits adds v to the "total_hits" field.
func (u *APIKeyReputationUpsert) AddTotalHits(v int) *APIKeyReputationUpsert {
	u.Add(apikeyreputation.FieldTotalHits, v)
	return u
}

// SetLastEventAt sets the "last_event_at" field.
func (u *APIKeyReputationUpsert) SetLastEventAt(v time.Time) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldLastEventAt, v)
	return u
}

// UpdateLastEventAt sets the "last_event_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateLastEventAt() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldLastEventAt)
	return u
}

// ClearLastEventAt clears the value of the "last_event_at" field.
func (u *APIKeyReputationUpsert) ClearLastEventAt() *APIKeyReputationUpsert {
	u.SetNull(apikeyreputation.FieldLastEventAt)
	return u
}

// SetScoredAt sets the "scored_at" field.
func (u *APIKeyReputationUpsert) SetScoredAt(v time.Time) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldScoredAt, v)
	return u
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateScoredAt() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldScoredAt)
	return u
}

// SetSanction sets the "sanction" field.
func (u *APIKeyReputationUpsert) SetSanction(v string) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldSanction, v)
	return u
}

// UpdateSanction sets the "sanction" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateSanction() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldSanction)
	return u
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (u *APIKeyReputationUpsert) SetSanctionedAt(v time.Time) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldSanctionedAt, v)
	return u
}

// UpdateSanctionedAt sets the "sanctioned_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateSanctionedAt() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldSanctionedAt)
	return u
}

// ClearSanctionedAt clears the value of the "sanctioned_at" field.
func (u *APIKeyReputationUpsert) ClearSanctionedAt() *APIKeyReputationUpsert {
	u.SetNull(apikeyreputation.FieldSanctionedAt)
	return u
}

// SetSanctionReason sets the "sanction_reason" field.
func (u *APIKeyReputationUpsert) SetSanctionReason(v string) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldSanctionReason, v)
	return u
}

// UpdateSanctionReason sets the "sanction_reason" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateSanctionReason() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldSanctionReason)
	return u
}

// ClearSanctionReason clears the value of the "sanction_reason" field.
func (u *APIKeyReputationUpsert) ClearSanctionReason() *APIKeyReputationUpsert {
	u.SetNull(apikeyreputation.FieldSanctionReason)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyReputationUpsert) SetUpdatedAt(v time.Time) *APIKeyReputationUpsert {
	u.Set(apikeyreputation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsert) UpdateUpdatedAt() *APIKeyReputationUpsert {
	u.SetExcluded(apikeyreputation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyReputationUpsertOne) UpdateNewValues() *APIKeyReputationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeyreputation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyReputationUpsertOne) Ignore() *APIKeyReputationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyReputationUpsertOne) DoNothing() *APIKeyReputationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyReputationCreate.OnConflict
// documentation for more info.
func (u *APIKeyReputationUpsertOne) Update(set func(*APIKeyReputationUpsert)) *APIKeyReputationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyReputationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyReputationUpsertOne) SetAPIKeyID(v int64) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeyReputationUpsertOne) AddAPIKeyID(v int64) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateAPIKeyID() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetScore sets the "score" field.
func (u *APIKeyReputationUpsertOne) SetScore(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *APIKeyReputationUpsertOne) AddScore(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateScore() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateScore()
	})
}

// SetSevereHits sets the "severe_hits" field.
func (u *APIKeyReputationUpsertOne) SetSevereHits(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSevereHits(v)
	})
}

// AddSevereHits adds v to the "severe_hits" field.
func (u *APIKeyReputationUpsertOne) AddSevereHits(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddSevereHits(v)
	})
}

// UpdateSevereHits sets the "severe_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateSevereHits() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSevereHits()
	})
}

// SetTotalHits sets the "total_hits" field.
func (u *APIKeyReputationUpsertOne) SetTotalHits(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetTotalHits(v)
	})
}

// AddTotalHits adds v to the "total_hits" field.
func (u *APIKeyReputationUpsertOne) AddTotalHits(v int) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddTotalHits(v)
	})
}

// UpdateTotalHits sets the "total_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateTotalHits() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateTotalHits()
	})
}

// SetLastEventAt sets the "last_event_at" field.
func (u *APIKeyReputationUpsertOne) SetLastEventAt(v time.Time) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetLastEventAt(v)
	})
}

// UpdateLastEventAt sets the "last_event_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateLastEventAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateLastEventAt()
	})
}

// ClearLastEventAt clears the value of the "last_event_at" field.
func (u *APIKeyReputationUpsertOne) ClearLastEventAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearLastEventAt()
	})
}

// SetScoredAt sets the "scored_at" field.
func (u *APIKeyReputationUpsertOne) SetScoredAt(v time.Time) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetScoredAt(v)
	})
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateScoredAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateScoredAt()
	})
}

// SetSanction sets the "sanction" field.
func (u *APIKeyReputationUpsertOne) SetSanction(v string) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanction(v)
	})
}

// UpdateSanction sets the "sanction" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateSanction() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanction()
	})
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (u *APIKeyReputationUpsertOne) SetSanctionedAt(v time.Time) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanctionedAt(v)
	})
}

// UpdateSanctionedAt sets the "sanctioned_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateSanctionedAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanctionedAt()
	})
}

// ClearSanctionedAt clears the value of the "sanctioned_at" field.
func (u *APIKeyReputationUpsertOne) ClearSanctionedAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearSanctionedAt()
	})
}

// SetSanctionReason sets the "sanction_reason" field.
func (u *APIKeyReputationUpsertOne) SetSanctionReason(v string) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanctionReason(v)
	})
}

// UpdateSanctionReason sets the "sanction_reason" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateSanctionReason() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanctionReason()
	})
}

// ClearSanctionReason clears the value of the "sanction_reason" field.
func (u *APIKeyReputationUpsertOne) ClearSanctionReason() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearSanctionReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyReputationUpsertOne) SetUpdatedAt(v time.Time) *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertOne) UpdateUpdatedAt() *APIKeyReputationUpsertOne {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyReputationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyReputationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyReputationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyReputationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyReputationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyReputationCreateBulk is the builder for creating many APIKeyReputation entities in bulk.
type APIKeyReputationCreateBulk struct {
	config
	err      error
	builders []*APIKeyReputationCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyReputation entities in the database.
func (_c *APIKeyReputationCreateBulk) Save(ctx context.Context) ([]*APIKeyReputation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyReputation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyReputationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyReputationCreateBulk) SaveX(ctx context.Context) []*APIKeyReputation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyReputationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyReputationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyReputation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyReputationUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyReputationCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyReputationUpsertBulk {
	_c.conflict = opts
	return &APIKeyReputationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyReputationCreateBulk) OnConflictColumns(columns ...string) *APIKeyReputationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyReputationUpsertBulk{
		create: _c,
	}
}

// APIKeyReputationUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyReputation nodes.
type APIKeyReputationUpsertBulk struct {
	create *APIKeyReputationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyReputationUpsertBulk) UpdateNewValues() *APIKeyReputationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeyreputation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyReputation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyReputationUpsertBulk) Ignore() *APIKeyReputationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyReputationUpsertBulk) DoNothing() *APIKeyReputationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyReputationCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyReputationUpsertBulk) Update(set func(*APIKeyReputationUpsert)) *APIKeyReputationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyReputationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyReputationUpsertBulk) SetAPIKeyID(v int64) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeyReputationUpsertBulk) AddAPIKeyID(v int64) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateAPIKeyID() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetScore sets the "score" field.
func (u *APIKeyReputationUpsertBulk) SetScore(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *APIKeyReputationUpsertBulk) AddScore(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateScore() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateScore()
	})
}

// SetSevereHits sets the "severe_hits" field.
func (u *APIKeyReputationUpsertBulk) SetSevereHits(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSevereHits(v)
	})
}

// AddSevereHits adds v to the "severe_hits" field.
func (u *APIKeyReputationUpsertBulk) AddSevereHits(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddSevereHits(v)
	})
}

// UpdateSevereHits sets the "severe_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateSevereHits() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSevereHits()
	})
}

// SetTotalHits sets the "total_hits" field.
func (u *APIKeyReputationUpsertBulk) SetTotalHits(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetTotalHits(v)
	})
}

// AddTotalHits adds v to the "total_hits" field.
func (u *APIKeyReputationUpsertBulk) AddTotalHits(v int) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.AddTotalHits(v)
	})
}

// UpdateTotalHits sets the "total_hits" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateTotalHits() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateTotalHits()
	})
}

// SetLastEventAt sets the "last_event_at" field.
func (u *APIKeyReputationUpsertBulk) SetLastEventAt(v time.Time) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetLastEventAt(v)
	})
}

// UpdateLastEventAt sets the "last_event_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateLastEventAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateLastEventAt()
	})
}

// ClearLastEventAt clears the value of the "last_event_at" field.
func (u *APIKeyReputationUpsertBulk) ClearLastEventAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearLastEventAt()
	})
}

// SetScoredAt sets the "scored_at" field.
func (u *APIKeyReputationUpsertBulk) SetScoredAt(v time.Time) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetScoredAt(v)
	})
}

// UpdateScoredAt sets the "scored_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateScoredAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateScoredAt()
	})
}

// SetSanction sets the "sanction" field.
func (u *APIKeyReputationUpsertBulk) SetSanction(v string) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanction(v)
	})
}

// UpdateSanction sets the "sanction" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateSanction() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanction()
	})
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (u *APIKeyReputationUpsertBulk) SetSanctionedAt(v time.Time) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanctionedAt(v)
	})
}

// UpdateSanctionedAt sets the "sanctioned_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateSanctionedAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanctionedAt()
	})
}

// ClearSanctionedAt clears the value of the "sanctioned_at" field.
func (u *APIKeyReputationUpsertBulk) ClearSanctionedAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearSanctionedAt()
	})
}

// SetSanctionReason sets the "sanction_reason" field.
func (u *APIKeyReputationUpsertBulk) SetSanctionReason(v string) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetSanctionReason(v)
	})
}

// UpdateSanctionReason sets the "sanction_reason" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateSanctionReason() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateSanctionReason()
	})
}

// ClearSanctionReason clears the value of the "sanction_reason" field.
func (u *APIKeyReputationUpsertBulk) ClearSanctionReason() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.ClearSanctionReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyReputationUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyReputationUpsertBulk) UpdateUpdatedAt() *APIKeyReputationUpsertBulk {
	return u.Update(func(s *APIKeyReputationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *APIKeyReputationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyReputationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyReputationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyReputationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
