// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikeyreputation"
)

// APIKeyReputation is the model entity for the APIKeyReputation schema.
type APIKeyReputation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// 100 = clean, 0 = worst
	Score int `json:"score,omitempty"`
	// SevereHits holds the value of the "severe_hits" field.
	SevereHits int `json:"severe_hits,omitempty"`
	// TotalHits holds the value of the "total_hits" field.
	TotalHits int `json:"total_hits,omitempty"`
	// LastEventAt holds the value of the "last_event_at" field.
	LastEventAt *time.Time `json:"last_event_at,omitempty"`
	// ScoredAt holds the value of the "scored_at" field.
	ScoredAt time.Time `json:"scored_at,omitempty"`
	// none | demoted | disabled
	Sanction string `json:"sanction,omitempty"`
	// SanctionedAt holds the value of the "sanctioned_at" field.
	SanctionedAt *time.Time `json:"sanctioned_at,omitempty"`
	// SanctionReason holds the value of the "sanction_reason" field.
	SanctionReason *string `json:"sanction_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyReputation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyreputation.FieldID, apikeyreputation.FieldAPIKeyID, apikeyreputation.FieldScore, apikeyreputation.FieldSevereHits, apikeyreputation.FieldTotalHits:
			values[i] = new(sql.NullInt64)
		case apikeyreputation.FieldSanction, apikeyreputation.FieldSanctionReason:
			values[i] = new(sql.NullString)
		case apikeyreputation.FieldLastEventAt, apikeyreputation.FieldScoredAt, apikeyreputation.FieldSanctionedAt, apikeyreputation.FieldCreatedAt, apikeyreputation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyReputation fields.
func (_m *APIKeyReputation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyreputation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case apikeyreputation.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeyreputation.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = int(value.Int64)
			}
		case apikeyreputation.FieldSevereHits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field severe_hits", values[i])
			} else if value.Valid {
				_m.SevereHits = int(value.Int64)
			}
		case apikeyreputation.FieldTotalHits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_hits", values[i])
			} else if value.Valid {
				_m.TotalHits = int(value.Int64)
			}
		case apikeyreputation.FieldLastEventAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_event_at", values[i])
			} else if value.Valid {
				_m.LastEventAt = new(time.Time)
				*_m.LastEventAt = value.Time
			}
		case apikeyreputation.FieldScoredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scored_at", values[i])
			} else if value.Valid {
				_m.ScoredAt = value.Time
			}
		case apikeyreputation.FieldSanction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sanction", values[i])
			} else if value.Valid {
				_m.Sanction = value.String
			}
		case apikeyreputation.FieldSanctionedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sanctioned_at", values[i])
			} else if value.Valid {
				_m.SanctionedAt = new(time.Time)
				*_m.SanctionedAt = value.Time
			}
		case apikeyreputation.FieldSanctionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sanction_reason", values[i])
			} else if value.Valid {
				_m.SanctionReason = new(string)
				*_m.SanctionReason = value.String
			}
		case apikeyreputation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyreputation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyReputation.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyReputation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this APIKeyReputation.
// Note that you need to call APIKeyReputation.Unwrap() before calling this method if this APIKeyReputation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyReputation) Update() *APIKeyReputationUpdateOne {
	return NewAPIKeyReputationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyReputation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyReputation) Unwrap() *APIKeyReputation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyReputation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyReputation) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyReputation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("severe_hits=")
	builder.WriteString(fmt.Sprintf("%v", _m.SevereHits))
	builder.WriteString(", ")
	builder.WriteString("total_hits=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalHits))
	builder.WriteString(", ")
	if v := _m.LastEventAt; v != nil {
		builder.WriteString("last_event_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("scored_at=")
	builder.WriteString(_m.ScoredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sanction=")
	builder.WriteString(_m.Sanction)
	builder.WriteString(", ")
	if v := _m.SanctionedAt; v != nil {
		builder.WriteString("sanctioned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SanctionReason; v != nil {
		builder.WriteString("sanction_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyReputations is a parsable slice of APIKeyReputation.
type APIKeyReputations []*APIKeyReputation
