// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeysubpoolbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeySubPoolBindingUpdate is the builder for updating APIKeySubPoolBinding entities.
type APIKeySubPoolBindingUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeySubPoolBindingMutation
}

// Where appends a list predicates to the APIKeySubPoolBindingUpdate builder.
func (_u *APIKeySubPoolBindingUpdate) Where(ps ...predicate.APIKeySubPoolBinding) *APIKeySubPoolBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeySubPoolBindingUpdate) SetAPIKeyID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableAPIKeyID(v *int64) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *APIKeySubPoolBindingUpdate) AddAPIKeyID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_u *APIKeySubPoolBindingUpdate) SetSubPoolID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.ResetSubPoolID()
	_u.mutation.SetSubPoolID(v)
	return _u
}

// SetNillableSubPoolID sets the "sub_pool_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableSubPoolID(v *int64) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetSubPoolID(*v)
	}
	return _u
}

// AddSubPoolID adds value to the "sub_pool_id" field.
func (_u *APIKeySubPoolBindingUpdate) AddSubPoolID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.AddSubPoolID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeySubPoolBindingUpdate) SetGroupID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableGroupID(v *int64) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *APIKeySubPoolBindingUpdate) AddGroupID(v int64) *APIKeySubPoolBindingUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *APIKeySubPoolBindingUpdate) SetBoundAt(v time.Time) *APIKeySubPoolBindingUpdate {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableBoundAt(v *time.Time) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetUnboundAt sets the "unbound_at" field.
func (_u *APIKeySubPoolBindingUpdate) SetUnboundAt(v time.Time) *APIKeySubPoolBindingUpdate {
	_u.mutation.SetUnboundAt(v)
	return _u
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableUnboundAt(v *time.Time) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetUnboundAt(*v)
	}
	return _u
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (_u *APIKeySubPoolBindingUpdate) ClearUnboundAt() *APIKeySubPoolBindingUpdate {
	_u.mutation.ClearUnboundAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *APIKeySubPoolBindingUpdate) SetReason(v string) *APIKeySubPoolBindingUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableReason(v *string) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *APIKeySubPoolBindingUpdate) SetOperator(v string) *APIKeySubPoolBindingUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableOperator(v *string) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *APIKeySubPoolBindingUpdate) SetNote(v string) *APIKeySubPoolBindingUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdate) SetNillableNote(v *string) *APIKeySubPoolBindingUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *APIKeySubPoolBindingUpdate) ClearNote() *APIKeySubPoolBindingUpdate {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the APIKeySubPoolBindingMutation object of the builder.
func (_u *APIKeySubPoolBindingUpdate) Mutation() *APIKeySubPoolBindingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeySubPoolBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeySubPoolBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeySubPoolBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeySubPoolBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeySubPoolBindingUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := apikeysubpoolbinding.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := apikeysubpoolbinding.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *APIKeySubPoolBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeysubpoolbinding.Table, apikeysubpoolbinding.Columns, sqlgraph.NewFieldSpec(apikeysubpoolbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubPoolID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldSubPoolID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubPoolID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldSubPoolID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnboundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldUnboundAt, field.TypeTime, value)
	}
	if _u.mutation.UnboundAtCleared() {
		_spec.ClearField(apikeysubpoolbinding.FieldUnboundAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(apikeysubpoolbinding.FieldNote, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeysubpoolbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeySubPoolBindingUpdateOne is the builder for updating a single APIKeySubPoolBinding entity.
type APIKeySubPoolBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeySubPoolBindingMutation
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetAPIKeyID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) AddAPIKeyID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetSubPoolID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.ResetSubPoolID()
	_u.mutation.SetSubPoolID(v)
	return _u
}

// SetNillableSubPoolID sets the "sub_pool_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableSubPoolID(v *int64) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetSubPoolID(*v)
	}
	return _u
}

// AddSubPoolID adds value to the "sub_pool_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) AddSubPoolID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.AddSubPoolID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetGroupID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableGroupID(v *int64) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *APIKeySubPoolBindingUpdateOne) AddGroupID(v int64) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetBoundAt sets the "bound_at" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetBoundAt(v time.Time) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.SetBoundAt(v)
	return _u
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableBoundAt(v *time.Time) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetBoundAt(*v)
	}
	return _u
}

// SetUnboundAt sets the "unbound_at" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetUnboundAt(v time.Time) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.SetUnboundAt(v)
	return _u
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableUnboundAt(v *time.Time) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetUnboundAt(*v)
	}
	return _u
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (_u *APIKeySubPoolBindingUpdateOne) ClearUnboundAt() *APIKeySubPoolBindingUpdateOne {
	_u.mutation.ClearUnboundAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetReason(v string) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableReason(v *string) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetOperator(v string) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableOperator(v *string) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *APIKeySubPoolBindingUpdateOne) SetNote(v string) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *APIKeySubPoolBindingUpdateOne) SetNillableNote(v *string) *APIKeySubPoolBindingUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *APIKeySubPoolBindingUpdateOne) ClearNote() *APIKeySubPoolBindingUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the APIKeySubPoolBindingMutation object of the builder.
func (_u *APIKeySubPoolBindingUpdateOne) Mutation() *APIKeySubPoolBindingMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeySubPoolBindingUpdate builder.
func (_u *APIKeySubPoolBindingUpdateOne) Where(ps ...predicate.APIKeySubPoolBinding) *APIKeySubPoolBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeySubPoolBindingUpdateOne) Select(field string, fields ...string) *APIKeySubPoolBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeySubPoolBinding entity.
func (_u *APIKeySubPoolBindingUpdateOne) Save(ctx context.Context) (*APIKeySubPoolBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeySubPoolBindingUpdateOne) SaveX(ctx context.Context) *APIKeySubPoolBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeySubPoolBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeySubPoolBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeySubPoolBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := apikeysubpoolbinding.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := apikeysubpoolbinding.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *APIKeySubPoolBindingUpdateOne) sqlSave(ctx context.Context) (_node *APIKeySubPoolBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeysubpoolbinding.Table, apikeysubpoolbinding.Columns, sqlgraph.NewFieldSpec(apikeysubpoolbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeySubPoolBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeysubpoolbinding.FieldID)
		for _, f := range fields {
			if !apikeysubpoolbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeysubpoolbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubPoolID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldSubPoolID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubPoolID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldSubPoolID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(apikeysubpoolbinding.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BoundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldBoundAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnboundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldUnboundAt, field.TypeTime, value)
	}
	if _u.mutation.UnboundAtCleared() {
		_spec.ClearField(apikeysubpoolbinding.FieldUnboundAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(apikeysubpoolbinding.FieldNote, field.TypeString)
	}
	_node = &APIKeySubPoolBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeysubpoolbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
