// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeyreputation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyReputationUpdate is the builder for updating APIKeyReputation entities.
type APIKeyReputationUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyReputationMutation
}

// Where appends a list predicates to the APIKeyReputationUpdate builder.
func (_u *APIKeyReputationUpdate) Where(ps ...predicate.APIKeyReputation) *APIKeyReputationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyReputationUpdate) SetAPIKeyID(v int64) *APIKeyReputationUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableAPIKeyID(v *int64) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *APIKeyReputationUpdate) AddAPIKeyID(v int64) *APIKeyReputationUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *APIKeyReputationUpdate) SetScore(v int) *APIKeyReputationUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableScore(v *int) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *APIKeyReputationUpdate) AddScore(v int) *APIKeyReputationUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetSevereHits sets the "severe_hits" field.
func (_u *APIKeyReputationUpdate) SetSevereHits(v int) *APIKeyReputationUpdate {
	_u.mutation.ResetSevereHits()
	_u.mutation.SetSevereHits(v)
	return _u
}

// SetNillableSevereHits sets the "severe_hits" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableSevereHits(v *int) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetSevereHits(*v)
	}
	return _u
}

// AddSevereHits adds value to the "severe_hits" field.
func (_u *APIKeyReputationUpdate) AddSevereHits(v int) *APIKeyReputationUpdate {
	_u.mutation.AddSevereHits(v)
	return _u
}

// SetTotalHits sets the "total_hits" field.
func (_u *APIKeyReputationUpdate) SetTotalHits(v int) *APIKeyReputationUpdate {
	_u.mutation.ResetTotalHits()
	_u.mutation.SetTotalHits(v)
	return _u
}

// SetNillableTotalHits sets the "total_hits" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableTotalHits(v *int) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetTotalHits(*v)
	}
	return _u
}

// AddTotalHits adds value to the "total_hits" field.
func (_u *APIKeyReputationUpdate) AddTotalHits(v int) *APIKeyReputationUpdate {
	_u.mutation.AddTotalHits(v)
	return _u
}

// SetLastEventAt sets the "last_event_at" field.
func (_u *APIKeyReputationUpdate) SetLastEventAt(v time.Time) *APIKeyReputationUpdate {
	_u.mutation.SetLastEventAt(v)
	return _u
}

// SetNillableLastEventAt sets the "last_event_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableLastEventAt(v *time.Time) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetLastEventAt(*v)
	}
	return _u
}

// ClearLastEventAt clears the value of the "last_event_at" field.
func (_u *APIKeyReputationUpdate) ClearLastEventAt() *APIKeyReputationUpdate {
	_u.mutation.ClearLastEventAt()
	return _u
}

// SetScoredAt sets the "scored_at" field.
func (_u *APIKeyReputationUpdate) SetScoredAt(v time.Time) *APIKeyReputationUpdate {
	_u.mutation.SetScoredAt(v)
	return _u
}

// SetNillableScoredAt sets the "scored_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableScoredAt(v *time.Time) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetScoredAt(*v)
	}
	return _u
}

// SetSanction sets the "sanction" field.
func (_u *APIKeyReputationUpdate) SetSanction(v string) *APIKeyReputationUpdate {
	_u.mutation.SetSanction(v)
	return _u
}

// SetNillableSanction sets the "sanction" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableSanction(v *string) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetSanction(*v)
	}
	return _u
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (_u *APIKeyReputationUpdate) SetSanctionedAt(v time.Time) *APIKeyReputationUpdate {
	_u.mutation.SetSanctionedAt(v)
	return _u
}

// SetNillableSanctionedAt sets the "sanctioned_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableSanctionedAt(v *time.Time) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetSanctionedAt(*v)
	}
	return _u
}

// ClearSanctionedAt clears the value of the "sanctioned_at" field.
func (_u *APIKeyReputationUpdate) ClearSanctionedAt() *APIKeyReputationUpdate {
	_u.mutation.ClearSanctionedAt()
	return _u
}

// SetSanctionReason sets the "sanction_reason" field.
func (_u *APIKeyReputationUpdate) SetSanctionReason(v string) *APIKeyReputationUpdate {
	_u.mutation.SetSanctionReason(v)
	return _u
}

// SetNillableSanctionReason sets the "sanction_reason" field if the given value is not nil.
func (_u *APIKeyReputationUpdate) SetNillableSanctionReason(v *string) *APIKeyReputationUpdate {
	if v != nil {
		_u.SetSanctionReason(*v)
	}
	return _u
}

// ClearSanctionReason clears the value of the "sanction_reason" field.
func (_u *APIKeyReputationUpdate) ClearSanctionReason() *APIKeyReputationUpdate {
	_u.mutation.ClearSanctionReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyReputationUpdate) SetUpdatedAt(v time.Time) *APIKeyReputationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the APIKeyReputationMutation object of the builder.
func (_u *APIKeyReputationUpdate) Mutation() *APIKeyReputationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyReputationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyReputationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyReputationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyReputationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyReputationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyreputation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyReputationUpdate) check() error {
	if v, ok := _u.mutation.Sanction(); ok {
		if err := apikeyreputation.SanctionValidator(v); err != nil {
			return &ValidationError{Name: "sanction", err: fmt.Errorf(`ent: validator failed for field "APIKeyReputation.sanction": %w`, err)}
		}
	}
	return nil
}

func (_u *APIKeyReputationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyreputation.Table, apikeyreputation.Columns, sqlgraph.NewFieldSpec(apikeyreputation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(apikeyreputation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(apikeyreputation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(apikeyreputation.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(apikeyreputation.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SevereHits(); ok {
		_spec.SetField(apikeyreputation.FieldSevereHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSevereHits(); ok {
		_spec.AddField(apikeyreputation.FieldSevereHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalHits(); ok {
		_spec.SetField(apikeyreputation.FieldTotalHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalHits(); ok {
		_spec.AddField(apikeyreputation.FieldTotalHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastEventAt(); ok {
		_spec.SetField(apikeyreputation.FieldLastEventAt, field.TypeTime, value)
	}
	if _u.mutation.LastEventAtCleared() {
		_spec.ClearField(apikeyreputation.FieldLastEventAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScoredAt(); ok {
		_spec.SetField(apikeyreputation.FieldScoredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sanction(); ok {
		_spec.SetField(apikeyreputation.FieldSanction, field.TypeString, value)
	}
	if value, ok := _u.mutation.SanctionedAt(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionedAt, field.TypeTime, value)
	}
	if _u.mutation.SanctionedAtCleared() {
		_spec.ClearField(apikeyreputation.FieldSanctionedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SanctionReason(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionReason, field.TypeString, value)
	}
	if _u.mutation.SanctionReasonCleared() {
		_spec.ClearField(apikeyreputation.FieldSanctionReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyreputation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyreputation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyReputationUpdateOne is the builder for updating a single APIKeyReputation entity.
type APIKeyReputationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyReputationMutation
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyReputationUpdateOne) SetAPIKeyID(v int64) *APIKeyReputationUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *APIKeyReputationUpdateOne) AddAPIKeyID(v int64) *APIKeyReputationUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *APIKeyReputationUpdateOne) SetScore(v int) *APIKeyReputationUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableScore(v *int) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *APIKeyReputationUpdateOne) AddScore(v int) *APIKeyReputationUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetSevereHits sets the "severe_hits" field.
func (_u *APIKeyReputationUpdateOne) SetSevereHits(v int) *APIKeyReputationUpdateOne {
	_u.mutation.ResetSevereHits()
	_u.mutation.SetSevereHits(v)
	return _u
}

// SetNillableSevereHits sets the "severe_hits" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableSevereHits(v *int) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetSevereHits(*v)
	}
	return _u
}

// AddSevereHits adds value to the "severe_hits" field.
func (_u *APIKeyReputationUpdateOne) AddSevereHits(v int) *APIKeyReputationUpdateOne {
	_u.mutation.AddSevereHits(v)
	return _u
}

// SetTotalHits sets the "total_hits" field.
func (_u *APIKeyReputationUpdateOne) SetTotalHits(v int) *APIKeyReputationUpdateOne {
	_u.mutation.ResetTotalHits()
	_u.mutation.SetTotalHits(v)
	return _u
}

// SetNillableTotalHits sets the "total_hits" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableTotalHits(v *int) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetTotalHits(*v)
	}
	return _u
}

// AddTotalHits adds value to the "total_hits" field.
func (_u *APIKeyReputationUpdateOne) AddTotalHits(v int) *APIKeyReputationUpdateOne {
	_u.mutation.AddTotalHits(v)
	return _u
}

// SetLastEventAt sets the "last_event_at" field.
func (_u *APIKeyReputationUpdateOne) SetLastEventAt(v time.Time) *APIKeyReputationUpdateOne {
	_u.mutation.SetLastEventAt(v)
	return _u
}

// SetNillableLastEventAt sets the "last_event_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableLastEventAt(v *time.Time) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetLastEventAt(*v)
	}
	return _u
}

// ClearLastEventAt clears the value of the "last_event_at" field.
func (_u *APIKeyReputationUpdateOne) ClearLastEventAt() *APIKeyReputationUpdateOne {
	_u.mutation.ClearLastEventAt()
	return _u
}

// SetScoredAt sets the "scored_at" field.
func (_u *APIKeyReputationUpdateOne) SetScoredAt(v time.Time) *APIKeyReputationUpdateOne {
	_u.mutation.SetScoredAt(v)
	return _u
}

// SetNillableScoredAt sets the "scored_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableScoredAt(v *time.Time) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetScoredAt(*v)
	}
	return _u
}

// SetSanction sets the "sanction" field.
func (_u *APIKeyReputationUpdateOne) SetSanction(v string) *APIKeyReputationUpdateOne {
	_u.mutation.SetSanction(v)
	return _u
}

// SetNillableSanction sets the "sanction" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableSanction(v *string) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetSanction(*v)
	}
	return _u
}

// SetSanctionedAt sets the "sanctioned_at" field.
func (_u *APIKeyReputationUpdateOne) SetSanctionedAt(v time.Time) *APIKeyReputationUpdateOne {
	_u.mutation.SetSanctionedAt(v)
	return _u
}

// SetNillableSanctionedAt sets the "sanctioned_at" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableSanctionedAt(v *time.Time) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetSanctionedAt(*v)
	}
	return _u
}

// ClearSanctionedAt clears the value of the "sanctioned_at" field.
func (_u *APIKeyReputationUpdateOne) ClearSanctionedAt() *APIKeyReputationUpdateOne {
	_u.mutation.ClearSanctionedAt()
	return _u
}

// SetSanctionReason sets the "sanction_reason" field.
func (_u *APIKeyReputationUpdateOne) SetSanctionReason(v string) *APIKeyReputationUpdateOne {
	_u.mutation.SetSanctionReason(v)
	return _u
}

// SetNillableSanctionReason sets the "sanction_reason" field if the given value is not nil.
func (_u *APIKeyReputationUpdateOne) SetNillableSanctionReason(v *string) *APIKeyReputationUpdateOne {
	if v != nil {
		_u.SetSanctionReason(*v)
	}
	return _u
}

// ClearSanctionReason clears the value of the "sanction_reason" field.
func (_u *APIKeyReputationUpdateOne) ClearSanctionReason() *APIKeyReputationUpdateOne {
	_u.mutation.ClearSanctionReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyReputationUpdateOne) SetUpdatedAt(v time.Time) *APIKeyReputationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the APIKeyReputationMutation object of the builder.
func (_u *APIKeyReputationUpdateOne) Mutation() *APIKeyReputationMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyReputationUpdate builder.
func (_u *APIKeyReputationUpdateOne) Where(ps ...predicate.APIKeyReputation) *APIKeyReputationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyReputationUpdateOne) Select(field string, fields ...string) *APIKeyReputationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyReputation entity.
func (_u *APIKeyReputationUpdateOne) Save(ctx context.Context) (*APIKeyReputation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyReputationUpdateOne) SaveX(ctx context.Context) *APIKeyReputation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyReputationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyReputationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyReputationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyreputation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyReputationUpdateOne) check() error {
	if v, ok := _u.mutation.Sanction(); ok {
		if err := apikeyreputation.SanctionValidator(v); err != nil {
			return &ValidationError{Name: "sanction", err: fmt.Errorf(`ent: validator failed for field "APIKeyReputation.sanction": %w`, err)}
		}
	}
	return nil
}

func (_u *APIKeyReputationUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyReputation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyreputation.Table, apikeyreputation.Columns, sqlgraph.NewFieldSpec(apikeyreputation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyReputation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeyreputation.FieldID)
		for _, f := range fields {
			if !apikeyreputation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeyreputation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(apikeyreputation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(apikeyreputation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(apikeyreputation.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(apikeyreputation.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SevereHits(); ok {
		_spec.SetField(apikeyreputation.FieldSevereHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSevereHits(); ok {
		_spec.AddField(apikeyreputation.FieldSevereHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalHits(); ok {
		_spec.SetField(apikeyreputation.FieldTotalHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalHits(); ok {
		_spec.AddField(apikeyreputation.FieldTotalHits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastEventAt(); ok {
		_spec.SetField(apikeyreputation.FieldLastEventAt, field.TypeTime, value)
	}
	if _u.mutation.LastEventAtCleared() {
		_spec.ClearField(apikeyreputation.FieldLastEventAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ScoredAt(); ok {
		_spec.SetField(apikeyreputation.FieldScoredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Sanction(); ok {
		_spec.SetField(apikeyreputation.FieldSanction, field.TypeString, value)
	}
	if value, ok := _u.mutation.SanctionedAt(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionedAt, field.TypeTime, value)
	}
	if _u.mutation.SanctionedAtCleared() {
		_spec.ClearField(apikeyreputation.FieldSanctionedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SanctionReason(); ok {
		_spec.SetField(apikeyreputation.FieldSanctionReason, field.TypeString, value)
	}
	if _u.mutation.SanctionReasonCleared() {
		_spec.ClearField(apikeyreputation.FieldSanctionReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyreputation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &APIKeyReputation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyreputation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
