// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikeysubpoolbinding"
)

// APIKeySubPoolBinding is the model entity for the APIKeySubPoolBinding schema.
type APIKeySubPoolBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// SubPoolID holds the value of the "sub_pool_id" field.
	SubPoolID int64 `json:"sub_pool_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt time.Time `json:"bound_at,omitempty"`
	// UnboundAt holds the value of the "unbound_at" field.
	UnboundAt *time.Time `json:"unbound_at,omitempty"`
	// initial | probe_graduation | cooling_migration | admin_manual | pool_removed
	Reason string `json:"reason,omitempty"`
	// 'system' or 'admin:<user_id>'
	Operator string `json:"operator,omitempty"`
	// Note holds the value of the "note" field.
	Note         *string `json:"note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeySubPoolBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeysubpoolbinding.FieldID, apikeysubpoolbinding.FieldAPIKeyID, apikeysubpoolbinding.FieldSubPoolID, apikeysubpoolbinding.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case apikeysubpoolbinding.FieldReason, apikeysubpoolbinding.FieldOperator, apikeysubpoolbinding.FieldNote:
			values[i] = new(sql.NullString)
		case apikeysubpoolbinding.FieldBoundAt, apikeysubpoolbinding.FieldUnboundAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeySubPoolBinding fields.
func (_m *APIKeySubPoolBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeysubpoolbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case apikeysubpoolbinding.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeysubpoolbinding.FieldSubPoolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_pool_id", values[i])
			} else if value.Valid {
				_m.SubPoolID = value.Int64
			}
		case apikeysubpoolbinding.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case apikeysubpoolbinding.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				_m.BoundAt = value.Time
			}
		case apikeysubpoolbinding.FieldUnboundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unbound_at", values[i])
			} else if value.Valid {
				_m.UnboundAt = new(time.Time)
				*_m.UnboundAt = value.Time
			}
		case apikeysubpoolbinding.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case apikeysubpoolbinding.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = value.String
			}
		case apikeysubpoolbinding.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeySubPoolBinding.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeySubPoolBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this APIKeySubPoolBinding.
// Note that you need to call APIKeySubPoolBinding.Unwrap() before calling this method if this APIKeySubPoolBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeySubPoolBinding) Update() *APIKeySubPoolBindingUpdateOne {
	return NewAPIKeySubPoolBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeySubPoolBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeySubPoolBinding) Unwrap() *APIKeySubPoolBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeySubPoolBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeySubPoolBinding) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeySubPoolBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("sub_pool_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubPoolID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("bound_at=")
	builder.WriteString(_m.BoundAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UnboundAt; v != nil {
		builder.WriteString("unbound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(_m.Operator)
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// APIKeySubPoolBindings is a parsable slice of APIKeySubPoolBinding.
type APIKeySubPoolBindings []*APIKeySubPoolBinding
