// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeysubpoolbinding"
)

// APIKeySubPoolBindingCreate is the builder for creating a APIKeySubPoolBinding entity.
type APIKeySubPoolBindingCreate struct {
	config
	mutation *APIKeySubPoolBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeySubPoolBindingCreate) SetAPIKeyID(v int64) *APIKeySubPoolBindingCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_c *APIKeySubPoolBindingCreate) SetSubPoolID(v int64) *APIKeySubPoolBindingCreate {
	_c.mutation.SetSubPoolID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *APIKeySubPoolBindingCreate) SetGroupID(v int64) *APIKeySubPoolBindingCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetBoundAt sets the "bound_at" field.
func (_c *APIKeySubPoolBindingCreate) SetBoundAt(v time.Time) *APIKeySubPoolBindingCreate {
	_c.mutation.SetBoundAt(v)
	return _c
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (_c *APIKeySubPoolBindingCreate) SetNillableBoundAt(v *time.Time) *APIKeySubPoolBindingCreate {
	if v != nil {
		_c.SetBoundAt(*v)
	}
	return _c
}

// SetUnboundAt sets the "unbound_at" field.
func (_c *APIKeySubPoolBindingCreate) SetUnboundAt(v time.Time) *APIKeySubPoolBindingCreate {
	_c.mutation.SetUnboundAt(v)
	return _c
}

// SetNillableUnboundAt sets the "unbound_at" field if the given value is not nil.
func (_c *APIKeySubPoolBindingCreate) SetNillableUnboundAt(v *time.Time) *APIKeySubPoolBindingCreate {
	if v != nil {
		_c.SetUnboundAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *APIKeySubPoolBindingCreate) SetReason(v string) *APIKeySubPoolBindingCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetOperator sets the "operator" field.
func (_c *APIKeySubPoolBindingCreate) SetOperator(v string) *APIKeySubPoolBindingCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_c *APIKeySubPoolBindingCreate) SetNillableOperator(v *string) *APIKeySubPoolBindingCreate {
	if v != nil {
		_c.SetOperator(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *APIKeySubPoolBindingCreate) SetNote(v string) *APIKeySubPoolBindingCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *APIKeySubPoolBindingCreate) SetNillableNote(v *string) *APIKeySubPoolBindingCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// Mutation returns the APIKeySubPoolBindingMutation object of the builder.
func (_c *APIKeySubPoolBindingCreate) Mutation() *APIKeySubPoolBindingMutation {
	return _c.mutation
}

// Save creates the APIKeySubPoolBinding in the database.
func (_c *APIKeySubPoolBindingCreate) Save(ctx context.Context) (*APIKeySubPoolBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeySubPoolBindingCreate) SaveX(ctx context.Context) *APIKeySubPoolBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeySubPoolBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeySubPoolBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeySubPoolBindingCreate) defaults() {
	if _, ok := _c.mutation.BoundAt(); !ok {
		v := apikeysubpoolbinding.DefaultBoundAt()
		_c.mutation.SetBoundAt(v)
	}
	if _, ok := _c.mutation.Operator(); !ok {
		v := apikeysubpoolbinding.DefaultOperator
		_c.mutation.SetOperator(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeySubPoolBindingCreate) check() error {
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.api_key_id"`)}
	}
	if _, ok := _c.mutation.SubPoolID(); !ok {
		return &ValidationError{Name: "sub_pool_id", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.sub_pool_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.group_id"`)}
	}
	if _, ok := _c.mutation.BoundAt(); !ok {
		return &ValidationError{Name: "bound_at", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.bound_at"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := apikeysubpoolbinding.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "APIKeySubPoolBinding.operator"`)}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := apikeysubpoolbinding.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "APIKeySubPoolBinding.operator": %w`, err)}
		}
	}
	return nil
}

func (_c *APIKeySubPoolBindingCreate) sqlSave(ctx context.Context) (*APIKeySubPoolBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeySubPoolBindingCreate) createSpec() (*APIKeySubPoolBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeySubPoolBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeysubpoolbinding.Table, sqlgraph.NewFieldSpec(apikeysubpoolbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.SubPoolID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldSubPoolID, field.TypeInt64, value)
		_node.SubPoolID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.BoundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldBoundAt, field.TypeTime, value)
		_node.BoundAt = value
	}
	if value, ok := _c.mutation.UnboundAt(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldUnboundAt, field.TypeTime, value)
		_node.UnboundAt = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldOperator, field.TypeString, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(apikeysubpoolbinding.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeySubPoolBinding.Create().
//		SetAPIKeyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeySubPoolBindingUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeySubPoolBindingCreate) OnConflict(opts ...sql.ConflictOption) *APIKeySubPoolBindingUpsertOne {
	_c.conflict = opts
	return &APIKeySubPoolBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeySubPoolBindingCreate) OnConflictColumns(columns ...string) *APIKeySubPoolBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeySubPoolBindingUpsertOne{
		create: _c,
	}
}

type (
	// APIKeySubPoolBindingUpsertOne is the builder for "upsert"-ing
	//  one APIKeySubPoolBinding node.
	APIKeySubPoolBindingUpsertOne struct {
		create *APIKeySubPoolBindingCreate
	}

	// APIKeySubPoolBindingUpsert is the "OnConflict" setter.
	APIKeySubPoolBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsert) SetAPIKeyID(v int64) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateAPIKeyID() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsert) AddAPIKeyID(v int64) *APIKeySubPoolBindingUpsert {
	u.Add(apikeysubpoolbinding.FieldAPIKeyID, v)
	return u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsert) SetSubPoolID(v int64) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldSubPoolID, v)
	return u
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateSubPoolID() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldSubPoolID)
	return u
}

// AddSubPoolID adds v to the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsert) AddSubPoolID(v int64) *APIKeySubPoolBindingUpsert {
	u.Add(apikeysubpoolbinding.FieldSubPoolID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *APIKeySubPoolBindingUpsert) SetGroupID(v int64) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateGroupID() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *APIKeySubPoolBindingUpsert) AddGroupID(v int64) *APIKeySubPoolBindingUpsert {
	u.Add(apikeysubpoolbinding.FieldGroupID, v)
	return u
}

// SetBoundAt sets the "bound_at" field.
func (u *APIKeySubPoolBindingUpsert) SetBoundAt(v time.Time) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldBoundAt, v)
	return u
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateBoundAt() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldBoundAt)
	return u
}

// SetUnboundAt sets the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsert) SetUnboundAt(v time.Time) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldUnboundAt, v)
	return u
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateUnboundAt() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldUnboundAt)
	return u
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsert) ClearUnboundAt() *APIKeySubPoolBindingUpsert {
	u.SetNull(apikeysubpoolbinding.FieldUnboundAt)
	return u
}

// SetReason sets the "reason" field.
func (u *APIKeySubPoolBindingUpsert) SetReason(v string) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateReason() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldReason)
	return u
}

// SetOperator sets the "operator" field.
func (u *APIKeySubPoolBindingUpsert) SetOperator(v string) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldOperator, v)
	return u
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateOperator() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldOperator)
	return u
}

// SetNote sets the "note" field.
func (u *APIKeySubPoolBindingUpsert) SetNote(v string) *APIKeySubPoolBindingUpsert {
	u.Set(apikeysubpoolbinding.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsert) UpdateNote() *APIKeySubPoolBindingUpsert {
	u.SetExcluded(apikeysubpoolbinding.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *APIKeySubPoolBindingUpsert) ClearNote() *APIKeySubPoolBindingUpsert {
	u.SetNull(apikeysubpoolbinding.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeySubPoolBindingUpsertOne) UpdateNewValues() *APIKeySubPoolBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeySubPoolBindingUpsertOne) Ignore() *APIKeySubPoolBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeySubPoolBindingUpsertOne) DoNothing() *APIKeySubPoolBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeySubPoolBindingCreate.OnConflict
// documentation for more info.
func (u *APIKeySubPoolBindingUpsertOne) Update(set func(*APIKeySubPoolBindingUpsert)) *APIKeySubPoolBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeySubPoolBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsertOne) SetAPIKeyID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsertOne) AddAPIKeyID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateAPIKeyID() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetSubPoolID sets the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsertOne) SetSubPoolID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetSubPoolID(v)
	})
}

// AddSubPoolID adds v to the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsertOne) AddSubPoolID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddSubPoolID(v)
	})
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateSubPoolID() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateSubPoolID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeySubPoolBindingUpsertOne) SetGroupID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *APIKeySubPoolBindingUpsertOne) AddGroupID(v int64) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateGroupID() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetBoundAt sets the "bound_at" field.
func (u *APIKeySubPoolBindingUpsertOne) SetBoundAt(v time.Time) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetBoundAt(v)
	})
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateBoundAt() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateBoundAt()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsertOne) SetUnboundAt(v time.Time) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateUnboundAt() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateUnboundAt()
	})
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsertOne) ClearUnboundAt() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.ClearUnboundAt()
	})
}

// SetReason sets the "reason" field.
func (u *APIKeySubPoolBindingUpsertOne) SetReason(v string) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateReason() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateReason()
	})
}

// SetOperator sets the "operator" field.
func (u *APIKeySubPoolBindingUpsertOne) SetOperator(v string) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateOperator() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateOperator()
	})
}

// SetNote sets the "note" field.
func (u *APIKeySubPoolBindingUpsertOne) SetNote(v string) *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertOne) UpdateNote() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *APIKeySubPoolBindingUpsertOne) ClearNote() *APIKeySubPoolBindingUpsertOne {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *APIKeySubPoolBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeySubPoolBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeySubPoolBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeySubPoolBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeySubPoolBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeySubPoolBindingCreateBulk is the builder for creating many APIKeySubPoolBinding entities in bulk.
type APIKeySubPoolBindingCreateBulk struct {
	config
	err      error
	builders []*APIKeySubPoolBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeySubPoolBinding entities in the database.
func (_c *APIKeySubPoolBindingCreateBulk) Save(ctx context.Context) ([]*APIKeySubPoolBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeySubPoolBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeySubPoolBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeySubPoolBindingCreateBulk) SaveX(ctx context.Context) []*APIKeySubPoolBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeySubPoolBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeySubPoolBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeySubPoolBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeySubPoolBindingUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeySubPoolBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeySubPoolBindingUpsertBulk {
	_c.conflict = opts
	return &APIKeySubPoolBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeySubPoolBindingCreateBulk) OnConflictColumns(columns ...string) *APIKeySubPoolBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeySubPoolBindingUpsertBulk{
		create: _c,
	}
}

// APIKeySubPoolBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeySubPoolBinding nodes.
type APIKeySubPoolBindingUpsertBulk struct {
	create *APIKeySubPoolBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeySubPoolBindingUpsertBulk) UpdateNewValues() *APIKeySubPoolBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeySubPoolBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeySubPoolBindingUpsertBulk) Ignore() *APIKeySubPoolBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeySubPoolBindingUpsertBulk) DoNothing() *APIKeySubPoolBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeySubPoolBindingCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeySubPoolBindingUpsertBulk) Update(set func(*APIKeySubPoolBindingUpsert)) *APIKeySubPoolBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeySubPoolBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetAPIKeyID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) AddAPIKeyID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateAPIKeyID() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetSubPoolID sets the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetSubPoolID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetSubPoolID(v)
	})
}

// AddSubPoolID adds v to the "sub_pool_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) AddSubPoolID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddSubPoolID(v)
	})
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateSubPoolID() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateSubPoolID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetGroupID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *APIKeySubPoolBindingUpsertBulk) AddGroupID(v int64) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateGroupID() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetBoundAt sets the "bound_at" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetBoundAt(v time.Time) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetBoundAt(v)
	})
}

// UpdateBoundAt sets the "bound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateBoundAt() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateBoundAt()
	})
}

// SetUnboundAt sets the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetUnboundAt(v time.Time) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetUnboundAt(v)
	})
}

// UpdateUnboundAt sets the "unbound_at" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateUnboundAt() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateUnboundAt()
	})
}

// ClearUnboundAt clears the value of the "unbound_at" field.
func (u *APIKeySubPoolBindingUpsertBulk) ClearUnboundAt() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.ClearUnboundAt()
	})
}

// SetReason sets the "reason" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetReason(v string) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateReason() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateReason()
	})
}

// SetOperator sets the "operator" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetOperator(v string) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateOperator() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateOperator()
	})
}

// SetNote sets the "note" field.
func (u *APIKeySubPoolBindingUpsertBulk) SetNote(v string) *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *APIKeySubPoolBindingUpsertBulk) UpdateNote() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *APIKeySubPoolBindingUpsertBulk) ClearNote() *APIKeySubPoolBindingUpsertBulk {
	return u.Update(func(s *APIKeySubPoolBindingUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *APIKeySubPoolBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeySubPoolBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeySubPoolBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeySubPoolBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
