// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
)

// SubPoolUpdate is the builder for updating SubPool entities.
type SubPoolUpdate struct {
	config
	hooks    []Hook
	mutation *SubPoolMutation
}

// Where appends a list predicates to the SubPoolUpdate builder.
func (_u *SubPoolUpdate) Where(ps ...predicate.SubPool) *SubPoolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubPoolUpdate) SetUpdatedAt(v time.Time) *SubPoolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubPoolUpdate) SetDeletedAt(v time.Time) *SubPoolUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableDeletedAt(v *time.Time) *SubPoolUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubPoolUpdate) ClearDeletedAt() *SubPoolUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubPoolUpdate) SetGroupID(v int64) *SubPoolUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableGroupID(v *int64) *SubPoolUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubPoolUpdate) AddGroupID(v int64) *SubPoolUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubPoolUpdate) SetName(v string) *SubPoolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableName(v *string) *SubPoolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubPoolUpdate) SetDescription(v string) *SubPoolUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableDescription(v *string) *SubPoolUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SubPoolUpdate) ClearDescription() *SubPoolUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubPoolUpdate) SetKind(v string) *SubPoolUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableKind(v *string) *SubPoolUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubPoolUpdate) SetStatus(v string) *SubPoolUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableStatus(v *string) *SubPoolUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (_u *SubPoolUpdate) SetKeySoftLimit(v int) *SubPoolUpdate {
	_u.mutation.ResetKeySoftLimit()
	_u.mutation.SetKeySoftLimit(v)
	return _u
}

// SetNillableKeySoftLimit sets the "key_soft_limit" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableKeySoftLimit(v *int) *SubPoolUpdate {
	if v != nil {
		_u.SetKeySoftLimit(*v)
	}
	return _u
}

// AddKeySoftLimit adds value to the "key_soft_limit" field.
func (_u *SubPoolUpdate) AddKeySoftLimit(v int) *SubPoolUpdate {
	_u.mutation.AddKeySoftLimit(v)
	return _u
}

// SetCoolingUntil sets the "cooling_until" field.
func (_u *SubPoolUpdate) SetCoolingUntil(v time.Time) *SubPoolUpdate {
	_u.mutation.SetCoolingUntil(v)
	return _u
}

// SetNillableCoolingUntil sets the "cooling_until" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableCoolingUntil(v *time.Time) *SubPoolUpdate {
	if v != nil {
		_u.SetCoolingUntil(*v)
	}
	return _u
}

// ClearCoolingUntil clears the value of the "cooling_until" field.
func (_u *SubPoolUpdate) ClearCoolingUntil() *SubPoolUpdate {
	_u.mutation.ClearCoolingUntil()
	return _u
}

// SetCoolingReason sets the "cooling_reason" field.
func (_u *SubPoolUpdate) SetCoolingReason(v string) *SubPoolUpdate {
	_u.mutation.SetCoolingReason(v)
	return _u
}

// SetNillableCoolingReason sets the "cooling_reason" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableCoolingReason(v *string) *SubPoolUpdate {
	if v != nil {
		_u.SetCoolingReason(*v)
	}
	return _u
}

// ClearCoolingReason clears the value of the "cooling_reason" field.
func (_u *SubPoolUpdate) ClearCoolingReason() *SubPoolUpdate {
	_u.mutation.ClearCoolingReason()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubPoolUpdate) SetSortOrder(v int) *SubPoolUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubPoolUpdate) SetNillableSortOrder(v *int) *SubPoolUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubPoolUpdate) AddSortOrder(v int) *SubPoolUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *SubPoolUpdate) AddAPIKeyIDs(ids ...int64) *SubPoolUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *SubPoolUpdate) AddAPIKeys(v ...*APIKey) *SubPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SubPoolUpdate) AddAccountIDs(ids ...int64) *SubPoolUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SubPoolUpdate) AddAccounts(v ...*Account) *SubPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the SubPoolMutation object of the builder.
func (_u *SubPoolUpdate) Mutation() *SubPoolMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *SubPoolUpdate) ClearAPIKeys() *SubPoolUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *SubPoolUpdate) RemoveAPIKeyIDs(ids ...int64) *SubPoolUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *SubPoolUpdate) RemoveAPIKeys(v ...*APIKey) *SubPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SubPoolUpdate) ClearAccounts() *SubPoolUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SubPoolUpdate) RemoveAccountIDs(ids ...int64) *SubPoolUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SubPoolUpdate) RemoveAccounts(v ...*Account) *SubPoolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubPoolUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubPoolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubPoolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubPoolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubPoolUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subpool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subpool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubPoolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := subpool.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubPool.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubPoolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subpool.Table, subpool.Columns, sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subpool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subpool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subpool.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subpool.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subpool.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(subpool.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subpool.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subpool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeySoftLimit(); ok {
		_spec.SetField(subpool.FieldKeySoftLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeySoftLimit(); ok {
		_spec.AddField(subpool.FieldKeySoftLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoolingUntil(); ok {
		_spec.SetField(subpool.FieldCoolingUntil, field.TypeTime, value)
	}
	if _u.mutation.CoolingUntilCleared() {
		_spec.ClearField(subpool.FieldCoolingUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CoolingReason(); ok {
		_spec.SetField(subpool.FieldCoolingReason, field.TypeString, value)
	}
	if _u.mutation.CoolingReasonCleared() {
		_spec.ClearField(subpool.FieldCoolingReason, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subpool.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subpool.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubPoolUpdateOne is the builder for updating a single SubPool entity.
type SubPoolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubPoolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubPoolUpdateOne) SetUpdatedAt(v time.Time) *SubPoolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubPoolUpdateOne) SetDeletedAt(v time.Time) *SubPoolUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableDeletedAt(v *time.Time) *SubPoolUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubPoolUpdateOne) ClearDeletedAt() *SubPoolUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubPoolUpdateOne) SetGroupID(v int64) *SubPoolUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableGroupID(v *int64) *SubPoolUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubPoolUpdateOne) AddGroupID(v int64) *SubPoolUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubPoolUpdateOne) SetName(v string) *SubPoolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableName(v *string) *SubPoolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubPoolUpdateOne) SetDescription(v string) *SubPoolUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableDescription(v *string) *SubPoolUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SubPoolUpdateOne) ClearDescription() *SubPoolUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetKind sets the "kind" field.
func (_u *SubPoolUpdateOne) SetKind(v string) *SubPoolUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableKind(v *string) *SubPoolUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubPoolUpdateOne) SetStatus(v string) *SubPoolUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableStatus(v *string) *SubPoolUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (_u *SubPoolUpdateOne) SetKeySoftLimit(v int) *SubPoolUpdateOne {
	_u.mutation.ResetKeySoftLimit()
	_u.mutation.SetKeySoftLimit(v)
	return _u
}

// SetNillableKeySoftLimit sets the "key_soft_limit" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableKeySoftLimit(v *int) *SubPoolUpdateOne {
	if v != nil {
		_u.SetKeySoftLimit(*v)
	}
	return _u
}

// AddKeySoftLimit adds value to the "key_soft_limit" field.
func (_u *SubPoolUpdateOne) AddKeySoftLimit(v int) *SubPoolUpdateOne {
	_u.mutation.AddKeySoftLimit(v)
	return _u
}

// SetCoolingUntil sets the "cooling_until" field.
func (_u *SubPoolUpdateOne) SetCoolingUntil(v time.Time) *SubPoolUpdateOne {
	_u.mutation.SetCoolingUntil(v)
	return _u
}

// SetNillableCoolingUntil sets the "cooling_until" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableCoolingUntil(v *time.Time) *SubPoolUpdateOne {
	if v != nil {
		_u.SetCoolingUntil(*v)
	}
	return _u
}

// ClearCoolingUntil clears the value of the "cooling_until" field.
func (_u *SubPoolUpdateOne) ClearCoolingUntil() *SubPoolUpdateOne {
	_u.mutation.ClearCoolingUntil()
	return _u
}

// SetCoolingReason sets the "cooling_reason" field.
func (_u *SubPoolUpdateOne) SetCoolingReason(v string) *SubPoolUpdateOne {
	_u.mutation.SetCoolingReason(v)
	return _u
}

// SetNillableCoolingReason sets the "cooling_reason" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableCoolingReason(v *string) *SubPoolUpdateOne {
	if v != nil {
		_u.SetCoolingReason(*v)
	}
	return _u
}

// ClearCoolingReason clears the value of the "cooling_reason" field.
func (_u *SubPoolUpdateOne) ClearCoolingReason() *SubPoolUpdateOne {
	_u.mutation.ClearCoolingReason()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubPoolUpdateOne) SetSortOrder(v int) *SubPoolUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubPoolUpdateOne) SetNillableSortOrder(v *int) *SubPoolUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubPoolUpdateOne) AddSortOrder(v int) *SubPoolUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *SubPoolUpdateOne) AddAPIKeyIDs(ids ...int64) *SubPoolUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *SubPoolUpdateOne) AddAPIKeys(v ...*APIKey) *SubPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SubPoolUpdateOne) AddAccountIDs(ids ...int64) *SubPoolUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SubPoolUpdateOne) AddAccounts(v ...*Account) *SubPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the SubPoolMutation object of the builder.
func (_u *SubPoolUpdateOne) Mutation() *SubPoolMutation {
	return _u.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *SubPoolUpdateOne) ClearAPIKeys() *SubPoolUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *SubPoolUpdateOne) RemoveAPIKeyIDs(ids ...int64) *SubPoolUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *SubPoolUpdateOne) RemoveAPIKeys(v ...*APIKey) *SubPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SubPoolUpdateOne) ClearAccounts() *SubPoolUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SubPoolUpdateOne) RemoveAccountIDs(ids ...int64) *SubPoolUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SubPoolUpdateOne) RemoveAccounts(v ...*Account) *SubPoolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the SubPoolUpdate builder.
func (_u *SubPoolUpdateOne) Where(ps ...predicate.SubPool) *SubPoolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubPoolUpdateOne) Select(field string, fields ...string) *SubPoolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubPool entity.
func (_u *SubPoolUpdateOne) Save(ctx context.Context) (*SubPool, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubPoolUpdateOne) SaveX(ctx context.Context) *SubPool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubPoolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubPoolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubPoolUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subpool.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subpool.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subpool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubPoolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubPool.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := subpool.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubPool.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubPool.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubPoolUpdateOne) sqlSave(ctx context.Context) (_node *SubPool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subpool.Table, subpool.Columns, sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubPool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subpool.FieldID)
		for _, f := range fields {
			if !subpool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subpool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subpool.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subpool.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subpool.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subpool.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subpool.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subpool.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(subpool.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(subpool.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subpool.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeySoftLimit(); ok {
		_spec.SetField(subpool.FieldKeySoftLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeySoftLimit(); ok {
		_spec.AddField(subpool.FieldKeySoftLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CoolingUntil(); ok {
		_spec.SetField(subpool.FieldCoolingUntil, field.TypeTime, value)
	}
	if _u.mutation.CoolingUntilCleared() {
		_spec.ClearField(subpool.FieldCoolingUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CoolingReason(); ok {
		_spec.SetField(subpool.FieldCoolingReason, field.TypeString, value)
	}
	if _u.mutation.CoolingReasonCleared() {
		_spec.ClearField(subpool.FieldCoolingReason, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subpool.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subpool.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SubPoolAccountCreate{config: _u.config, mutation: newSubPoolAccountMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubPool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subpool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
