// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
	"github.com/Wei-Shaw/sub2api/ent/subpoolaccount"
)

// SubPoolAccountUpdate is the builder for updating SubPoolAccount entities.
type SubPoolAccountUpdate struct {
	config
	hooks    []Hook
	mutation *SubPoolAccountMutation
}

// Where appends a list predicates to the SubPoolAccountUpdate builder.
func (_u *SubPoolAccountUpdate) Where(ps ...predicate.SubPoolAccount) *SubPoolAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_u *SubPoolAccountUpdate) SetSubPoolID(v int64) *SubPoolAccountUpdate {
	_u.mutation.SetSubPoolID(v)
	return _u
}

// SetNillableSubPoolID sets the "sub_pool_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdate) SetNillableSubPoolID(v *int64) *SubPoolAccountUpdate {
	if v != nil {
		_u.SetSubPoolID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SubPoolAccountUpdate) SetAccountID(v int64) *SubPoolAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdate) SetNillableAccountID(v *int64) *SubPoolAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubPoolAccountUpdate) SetGroupID(v int64) *SubPoolAccountUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdate) SetNillableGroupID(v *int64) *SubPoolAccountUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubPoolAccountUpdate) AddGroupID(v int64) *SubPoolAccountUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SubPoolAccountUpdate) SetRole(v string) *SubPoolAccountUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SubPoolAccountUpdate) SetNillableRole(v *string) *SubPoolAccountUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSubPool sets the "sub_pool" edge to the SubPool entity.
func (_u *SubPoolAccountUpdate) SetSubPool(v *SubPool) *SubPoolAccountUpdate {
	return _u.SetSubPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *SubPoolAccountUpdate) SetAccount(v *Account) *SubPoolAccountUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the SubPoolAccountMutation object of the builder.
func (_u *SubPoolAccountUpdate) Mutation() *SubPoolAccountMutation {
	return _u.mutation
}

// ClearSubPool clears the "sub_pool" edge to the SubPool entity.
func (_u *SubPoolAccountUpdate) ClearSubPool() *SubPoolAccountUpdate {
	_u.mutation.ClearSubPool()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *SubPoolAccountUpdate) ClearAccount() *SubPoolAccountUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubPoolAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubPoolAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubPoolAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubPoolAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubPoolAccountUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := subpoolaccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SubPoolAccount.role": %w`, err)}
		}
	}
	if _u.mutation.SubPoolCleared() && len(_u.mutation.SubPoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubPoolAccount.sub_pool"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubPoolAccount.account"`)
	}
	return nil
}

func (_u *SubPoolAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subpoolaccount.Table, subpoolaccount.Columns, sqlgraph.NewFieldSpec(subpoolaccount.FieldSubPoolID, field.TypeInt64), sqlgraph.NewFieldSpec(subpoolaccount.FieldAccountID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subpoolaccount.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subpoolaccount.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(subpoolaccount.FieldRole, field.TypeString, value)
	}
	if _u.mutation.SubPoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.SubPoolTable,
			Columns: []string{subpoolaccount.SubPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubPoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.SubPoolTable,
			Columns: []string{subpoolaccount.SubPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.AccountTable,
			Columns: []string{subpoolaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.AccountTable,
			Columns: []string{subpoolaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subpoolaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubPoolAccountUpdateOne is the builder for updating a single SubPoolAccount entity.
type SubPoolAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubPoolAccountMutation
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_u *SubPoolAccountUpdateOne) SetSubPoolID(v int64) *SubPoolAccountUpdateOne {
	_u.mutation.SetSubPoolID(v)
	return _u
}

// SetNillableSubPoolID sets the "sub_pool_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdateOne) SetNillableSubPoolID(v *int64) *SubPoolAccountUpdateOne {
	if v != nil {
		_u.SetSubPoolID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *SubPoolAccountUpdateOne) SetAccountID(v int64) *SubPoolAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdateOne) SetNillableAccountID(v *int64) *SubPoolAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubPoolAccountUpdateOne) SetGroupID(v int64) *SubPoolAccountUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubPoolAccountUpdateOne) SetNillableGroupID(v *int64) *SubPoolAccountUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubPoolAccountUpdateOne) AddGroupID(v int64) *SubPoolAccountUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SubPoolAccountUpdateOne) SetRole(v string) *SubPoolAccountUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SubPoolAccountUpdateOne) SetNillableRole(v *string) *SubPoolAccountUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSubPool sets the "sub_pool" edge to the SubPool entity.
func (_u *SubPoolAccountUpdateOne) SetSubPool(v *SubPool) *SubPoolAccountUpdateOne {
	return _u.SetSubPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *SubPoolAccountUpdateOne) SetAccount(v *Account) *SubPoolAccountUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the SubPoolAccountMutation object of the builder.
func (_u *SubPoolAccountUpdateOne) Mutation() *SubPoolAccountMutation {
	return _u.mutation
}

// ClearSubPool clears the "sub_pool" edge to the SubPool entity.
func (_u *SubPoolAccountUpdateOne) ClearSubPool() *SubPoolAccountUpdateOne {
	_u.mutation.ClearSubPool()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *SubPoolAccountUpdateOne) ClearAccount() *SubPoolAccountUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the SubPoolAccountUpdate builder.
func (_u *SubPoolAccountUpdateOne) Where(ps ...predicate.SubPoolAccount) *SubPoolAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubPoolAccountUpdateOne) Select(field string, fields ...string) *SubPoolAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubPoolAccount entity.
func (_u *SubPoolAccountUpdateOne) Save(ctx context.Context) (*SubPoolAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubPoolAccountUpdateOne) SaveX(ctx context.Context) *SubPoolAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubPoolAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubPoolAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubPoolAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := subpoolaccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SubPoolAccount.role": %w`, err)}
		}
	}
	if _u.mutation.SubPoolCleared() && len(_u.mutation.SubPoolIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubPoolAccount.sub_pool"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubPoolAccount.account"`)
	}
	return nil
}

func (_u *SubPoolAccountUpdateOne) sqlSave(ctx context.Context) (_node *SubPoolAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subpoolaccount.Table, subpoolaccount.Columns, sqlgraph.NewFieldSpec(subpoolaccount.FieldSubPoolID, field.TypeInt64), sqlgraph.NewFieldSpec(subpoolaccount.FieldAccountID, field.TypeInt64))
	if id, ok := _u.mutation.SubPoolID(); !ok {
		return nil, &ValidationError{Name: "sub_pool_id", err: errors.New(`ent: missing "SubPoolAccount.sub_pool_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "SubPoolAccount.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !subpoolaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subpoolaccount.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subpoolaccount.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(subpoolaccount.FieldRole, field.TypeString, value)
	}
	if _u.mutation.SubPoolCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.SubPoolTable,
			Columns: []string{subpoolaccount.SubPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubPoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.SubPoolTable,
			Columns: []string{subpoolaccount.SubPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.AccountTable,
			Columns: []string{subpoolaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.AccountTable,
			Columns: []string{subpoolaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubPoolAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subpoolaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
