// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
)

// SubPool is the model entity for the SubPool schema.
type SubPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// formal | probe (probe pools use disposable accounts)
	Kind string `json:"kind,omitempty"`
	// healthy | cooling | closed
	Status string `json:"status,omitempty"`
	// Soft cap on bound API keys; 0 means unlimited
	KeySoftLimit int `json:"key_soft_limit,omitempty"`
	// CoolingUntil holds the value of the "cooling_until" field.
	CoolingUntil *time.Time `json:"cooling_until,omitempty"`
	// CoolingReason holds the value of the "cooling_reason" field.
	CoolingReason *string `json:"cooling_reason,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubPoolQuery when eager-loading is set.
	Edges        SubPoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubPoolEdges holds the relations/edges for other nodes in the graph.
type SubPoolEdges struct {
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// SubPoolAccounts holds the value of the sub_pool_accounts edge.
	SubPoolAccounts []*SubPoolAccount `json:"sub_pool_accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e SubPoolEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[0] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e SubPoolEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// SubPoolAccountsOrErr returns the SubPoolAccounts value or an error if the edge
// was not loaded in eager-loading.
func (e SubPoolEdges) SubPoolAccountsOrErr() ([]*SubPoolAccount, error) {
	if e.loadedTypes[2] {
		return e.SubPoolAccounts, nil
	}
	return nil, &NotLoadedError{edge: "sub_pool_accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subpool.FieldID, subpool.FieldGroupID, subpool.FieldKeySoftLimit, subpool.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case subpool.FieldName, subpool.FieldDescription, subpool.FieldKind, subpool.FieldStatus, subpool.FieldCoolingReason:
			values[i] = new(sql.NullString)
		case subpool.FieldCreatedAt, subpool.FieldUpdatedAt, subpool.FieldDeletedAt, subpool.FieldCoolingUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubPool fields.
func (_m *SubPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subpool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subpool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subpool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subpool.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case subpool.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subpool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subpool.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case subpool.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case subpool.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subpool.FieldKeySoftLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field key_soft_limit", values[i])
			} else if value.Valid {
				_m.KeySoftLimit = int(value.Int64)
			}
		case subpool.FieldCoolingUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooling_until", values[i])
			} else if value.Valid {
				_m.CoolingUntil = new(time.Time)
				*_m.CoolingUntil = value.Time
			}
		case subpool.FieldCoolingReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cooling_reason", values[i])
			} else if value.Valid {
				_m.CoolingReason = new(string)
				*_m.CoolingReason = value.String
			}
		case subpool.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubPool.
// This includes values selected through modifiers, order, etc.
func (_m *SubPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKeys queries the "api_keys" edge of the SubPool entity.
func (_m *SubPool) QueryAPIKeys() *APIKeyQuery {
	return NewSubPoolClient(_m.config).QueryAPIKeys(_m)
}

// QueryAccounts queries the "accounts" edge of the SubPool entity.
func (_m *SubPool) QueryAccounts() *AccountQuery {
	return NewSubPoolClient(_m.config).QueryAccounts(_m)
}

// QuerySubPoolAccounts queries the "sub_pool_accounts" edge of the SubPool entity.
func (_m *SubPool) QuerySubPoolAccounts() *SubPoolAccountQuery {
	return NewSubPoolClient(_m.config).QuerySubPoolAccounts(_m)
}

// Update returns a builder for updating this SubPool.
// Note that you need to call SubPool.Unwrap() before calling this method if this SubPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubPool) Update() *SubPoolUpdateOne {
	return NewSubPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubPool) Unwrap() *SubPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubPool) String() string {
	var builder strings.Builder
	builder.WriteString("SubPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("key_soft_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.KeySoftLimit))
	builder.WriteString(", ")
	if v := _m.CoolingUntil; v != nil {
		builder.WriteString("cooling_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CoolingReason; v != nil {
		builder.WriteString("cooling_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// SubPools is a parsable slice of SubPool.
type SubPools []*SubPool
