// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
)

// SubPoolCreate is the builder for creating a SubPool entity.
type SubPoolCreate struct {
	config
	mutation *SubPoolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubPoolCreate) SetCreatedAt(v time.Time) *SubPoolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableCreatedAt(v *time.Time) *SubPoolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubPoolCreate) SetUpdatedAt(v time.Time) *SubPoolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableUpdatedAt(v *time.Time) *SubPoolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubPoolCreate) SetDeletedAt(v time.Time) *SubPoolCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableDeletedAt(v *time.Time) *SubPoolCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubPoolCreate) SetGroupID(v int64) *SubPoolCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SubPoolCreate) SetName(v string) *SubPoolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SubPoolCreate) SetDescription(v string) *SubPoolCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableDescription(v *string) *SubPoolCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *SubPoolCreate) SetKind(v string) *SubPoolCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableKind(v *string) *SubPoolCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubPoolCreate) SetStatus(v string) *SubPoolCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableStatus(v *string) *SubPoolCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (_c *SubPoolCreate) SetKeySoftLimit(v int) *SubPoolCreate {
	_c.mutation.SetKeySoftLimit(v)
	return _c
}

// SetNillableKeySoftLimit sets the "key_soft_limit" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableKeySoftLimit(v *int) *SubPoolCreate {
	if v != nil {
		_c.SetKeySoftLimit(*v)
	}
	return _c
}

// SetCoolingUntil sets the "cooling_until" field.
func (_c *SubPoolCreate) SetCoolingUntil(v time.Time) *SubPoolCreate {
	_c.mutation.SetCoolingUntil(v)
	return _c
}

// SetNillableCoolingUntil sets the "cooling_until" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableCoolingUntil(v *time.Time) *SubPoolCreate {
	if v != nil {
		_c.SetCoolingUntil(*v)
	}
	return _c
}

// SetCoolingReason sets the "cooling_reason" field.
func (_c *SubPoolCreate) SetCoolingReason(v string) *SubPoolCreate {
	_c.mutation.SetCoolingReason(v)
	return _c
}

// SetNillableCoolingReason sets the "cooling_reason" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableCoolingReason(v *string) *SubPoolCreate {
	if v != nil {
		_c.SetCoolingReason(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *SubPoolCreate) SetSortOrder(v int) *SubPoolCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *SubPoolCreate) SetNillableSortOrder(v *int) *SubPoolCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *SubPoolCreate) AddAPIKeyIDs(ids ...int64) *SubPoolCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *SubPoolCreate) AddAPIKeys(v ...*APIKey) *SubPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *SubPoolCreate) AddAccountIDs(ids ...int64) *SubPoolCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *SubPoolCreate) AddAccounts(v ...*Account) *SubPoolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the SubPoolMutation object of the builder.
func (_c *SubPoolCreate) Mutation() *SubPoolMutation {
	return _c.mutation
}

// Save creates the SubPool in the database.
func (_c *SubPoolCreate) Save(ctx context.Context) (*SubPool, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubPoolCreate) SaveX(ctx context.Context) *SubPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubPoolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubPoolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubPoolCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subpool.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized subpool.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := subpool.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subpool.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subpool.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subpool.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := subpool.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subpool.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.KeySoftLimit(); !ok {
		v := subpool.DefaultKeySoftLimit
		_c.mutation.SetKeySoftLimit(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := subpool.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubPoolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubPool.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubPool.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubPool.group_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SubPool.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subpool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubPool.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "SubPool.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := subpool.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubPool.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubPool.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subpool.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubPool.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeySoftLimit(); !ok {
		return &ValidationError{Name: "key_soft_limit", err: errors.New(`ent: missing required field "SubPool.key_soft_limit"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "SubPool.sort_order"`)}
	}
	return nil
}

func (_c *SubPoolCreate) sqlSave(ctx context.Context) (*SubPool, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubPoolCreate) createSpec() (*SubPool, *sqlgraph.CreateSpec) {
	var (
		_node = &SubPool{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subpool.Table, sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subpool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subpool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subpool.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(subpool.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subpool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(subpool.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(subpool.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subpool.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.KeySoftLimit(); ok {
		_spec.SetField(subpool.FieldKeySoftLimit, field.TypeInt, value)
		_node.KeySoftLimit = value
	}
	if value, ok := _c.mutation.CoolingUntil(); ok {
		_spec.SetField(subpool.FieldCoolingUntil, field.TypeTime, value)
		_node.CoolingUntil = &value
	}
	if value, ok := _c.mutation.CoolingReason(); ok {
		_spec.SetField(subpool.FieldCoolingReason, field.TypeString, value)
		_node.CoolingReason = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(subpool.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subpool.APIKeysTable,
			Columns: []string{subpool.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   subpool.AccountsTable,
			Columns: subpool.AccountsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SubPoolAccountCreate{config: _c.config, mutation: newSubPoolAccountMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubPool.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubPoolCreate) OnConflict(opts ...sql.ConflictOption) *SubPoolUpsertOne {
	_c.conflict = opts
	return &SubPoolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubPoolCreate) OnConflictColumns(columns ...string) *SubPoolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubPoolUpsertOne{
		create: _c,
	}
}

type (
	// SubPoolUpsertOne is the builder for "upsert"-ing
	//  one SubPool node.
	SubPoolUpsertOne struct {
		create *SubPoolCreate
	}

	// SubPoolUpsert is the "OnConflict" setter.
	SubPoolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubPoolUpsert) SetUpdatedAt(v time.Time) *SubPoolUpsert {
	u.Set(subpool.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateUpdatedAt() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubPoolUpsert) SetDeletedAt(v time.Time) *SubPoolUpsert {
	u.Set(subpool.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateDeletedAt() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubPoolUpsert) ClearDeletedAt() *SubPoolUpsert {
	u.SetNull(subpool.FieldDeletedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolUpsert) SetGroupID(v int64) *SubPoolUpsert {
	u.Set(subpool.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateGroupID() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolUpsert) AddGroupID(v int64) *SubPoolUpsert {
	u.Add(subpool.FieldGroupID, v)
	return u
}

// SetName sets the "name" field.
func (u *SubPoolUpsert) SetName(v string) *SubPoolUpsert {
	u.Set(subpool.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateName() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SubPoolUpsert) SetDescription(v string) *SubPoolUpsert {
	u.Set(subpool.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateDescription() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SubPoolUpsert) ClearDescription() *SubPoolUpsert {
	u.SetNull(subpool.FieldDescription)
	return u
}

// SetKind sets the "kind" field.
func (u *SubPoolUpsert) SetKind(v string) *SubPoolUpsert {
	u.Set(subpool.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateKind() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldKind)
	return u
}

// SetStatus sets the "status" field.
func (u *SubPoolUpsert) SetStatus(v string) *SubPoolUpsert {
	u.Set(subpool.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateStatus() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldStatus)
	return u
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (u *SubPoolUpsert) SetKeySoftLimit(v int) *SubPoolUpsert {
	u.Set(subpool.FieldKeySoftLimit, v)
	return u
}

// UpdateKeySoftLimit sets the "key_soft_limit" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateKeySoftLimit() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldKeySoftLimit)
	return u
}

// AddKeySoftLimit adds v to the "key_soft_limit" field.
func (u *SubPoolUpsert) AddKeySoftLimit(v int) *SubPoolUpsert {
	u.Add(subpool.FieldKeySoftLimit, v)
	return u
}

// SetCoolingUntil sets the "cooling_until" field.
func (u *SubPoolUpsert) SetCoolingUntil(v time.Time) *SubPoolUpsert {
	u.Set(subpool.FieldCoolingUntil, v)
	return u
}

// UpdateCoolingUntil sets the "cooling_until" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateCoolingUntil() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldCoolingUntil)
	return u
}

// ClearCoolingUntil clears the value of the "cooling_until" field.
func (u *SubPoolUpsert) ClearCoolingUntil() *SubPoolUpsert {
	u.SetNull(subpool.FieldCoolingUntil)
	return u
}

// SetCoolingReason sets the "cooling_reason" field.
func (u *SubPoolUpsert) SetCoolingReason(v string) *SubPoolUpsert {
	u.Set(subpool.FieldCoolingReason, v)
	return u
}

// UpdateCoolingReason sets the "cooling_reason" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateCoolingReason() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldCoolingReason)
	return u
}

// ClearCoolingReason clears the value of the "cooling_reason" field.
func (u *SubPoolUpsert) ClearCoolingReason() *SubPoolUpsert {
	u.SetNull(subpool.FieldCoolingReason)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *SubPoolUpsert) SetSortOrder(v int) *SubPoolUpsert {
	u.Set(subpool.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubPoolUpsert) UpdateSortOrder() *SubPoolUpsert {
	u.SetExcluded(subpool.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubPoolUpsert) AddSortOrder(v int) *SubPoolUpsert {
	u.Add(subpool.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubPoolUpsertOne) UpdateNewValues() *SubPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subpool.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubPool.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubPoolUpsertOne) Ignore() *SubPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubPoolUpsertOne) DoNothing() *SubPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubPoolCreate.OnConflict
// documentation for more info.
func (u *SubPoolUpsertOne) Update(set func(*SubPoolUpsert)) *SubPoolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubPoolUpsertOne) SetUpdatedAt(v time.Time) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateUpdatedAt() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubPoolUpsertOne) SetDeletedAt(v time.Time) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateDeletedAt() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubPoolUpsertOne) ClearDeletedAt() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolUpsertOne) SetGroupID(v int64) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolUpsertOne) AddGroupID(v int64) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateGroupID() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateGroupID()
	})
}

// SetName sets the "name" field.
func (u *SubPoolUpsertOne) SetName(v string) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateName() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubPoolUpsertOne) SetDescription(v string) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateDescription() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubPoolUpsertOne) ClearDescription() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearDescription()
	})
}

// SetKind sets the "kind" field.
func (u *SubPoolUpsertOne) SetKind(v string) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateKind() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *SubPoolUpsertOne) SetStatus(v string) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateStatus() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (u *SubPoolUpsertOne) SetKeySoftLimit(v int) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetKeySoftLimit(v)
	})
}

// AddKeySoftLimit adds v to the "key_soft_limit" field.
func (u *SubPoolUpsertOne) AddKeySoftLimit(v int) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddKeySoftLimit(v)
	})
}

// UpdateKeySoftLimit sets the "key_soft_limit" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateKeySoftLimit() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateKeySoftLimit()
	})
}

// SetCoolingUntil sets the "cooling_until" field.
func (u *SubPoolUpsertOne) SetCoolingUntil(v time.Time) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetCoolingUntil(v)
	})
}

// UpdateCoolingUntil sets the "cooling_until" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateCoolingUntil() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateCoolingUntil()
	})
}

// ClearCoolingUntil clears the value of the "cooling_until" field.
func (u *SubPoolUpsertOne) ClearCoolingUntil() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearCoolingUntil()
	})
}

// SetCoolingReason sets the "cooling_reason" field.
func (u *SubPoolUpsertOne) SetCoolingReason(v string) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetCoolingReason(v)
	})
}

// UpdateCoolingReason sets the "cooling_reason" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateCoolingReason() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateCoolingReason()
	})
}

// ClearCoolingReason clears the value of the "cooling_reason" field.
func (u *SubPoolUpsertOne) ClearCoolingReason() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearCoolingReason()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubPoolUpsertOne) SetSortOrder(v int) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubPoolUpsertOne) AddSortOrder(v int) *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubPoolUpsertOne) UpdateSortOrder() *SubPoolUpsertOne {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubPoolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubPoolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubPoolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubPoolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubPoolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubPoolCreateBulk is the builder for creating many SubPool entities in bulk.
type SubPoolCreateBulk struct {
	config
	err      error
	builders []*SubPoolCreate
	conflict []sql.ConflictOption
}

// Save creates the SubPool entities in the database.
func (_c *SubPoolCreateBulk) Save(ctx context.Context) ([]*SubPool, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubPool, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubPoolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubPoolCreateBulk) SaveX(ctx context.Context) []*SubPool {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubPoolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubPoolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubPool.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubPoolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubPoolCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubPoolUpsertBulk {
	_c.conflict = opts
	return &SubPoolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubPool.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubPoolCreateBulk) OnConflictColumns(columns ...string) *SubPoolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubPoolUpsertBulk{
		create: _c,
	}
}

// SubPoolUpsertBulk is the builder for "upsert"-ing
// a bulk of SubPool nodes.
type SubPoolUpsertBulk struct {
	create *SubPoolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubPool.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubPoolUpsertBulk) UpdateNewValues() *SubPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subpool.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubPool.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubPoolUpsertBulk) Ignore() *SubPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubPoolUpsertBulk) DoNothing() *SubPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubPoolCreateBulk.OnConflict
// documentation for more info.
func (u *SubPoolUpsertBulk) Update(set func(*SubPoolUpsert)) *SubPoolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubPoolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubPoolUpsertBulk) SetUpdatedAt(v time.Time) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateUpdatedAt() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubPoolUpsertBulk) SetDeletedAt(v time.Time) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateDeletedAt() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubPoolUpsertBulk) ClearDeletedAt() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearDeletedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolUpsertBulk) SetGroupID(v int64) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolUpsertBulk) AddGroupID(v int64) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateGroupID() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateGroupID()
	})
}

// SetName sets the "name" field.
func (u *SubPoolUpsertBulk) SetName(v string) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateName() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SubPoolUpsertBulk) SetDescription(v string) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateDescription() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubPoolUpsertBulk) ClearDescription() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearDescription()
	})
}

// SetKind sets the "kind" field.
func (u *SubPoolUpsertBulk) SetKind(v string) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateKind() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *SubPoolUpsertBulk) SetStatus(v string) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateStatus() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateStatus()
	})
}

// SetKeySoftLimit sets the "key_soft_limit" field.
func (u *SubPoolUpsertBulk) SetKeySoftLimit(v int) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetKeySoftLimit(v)
	})
}

// AddKeySoftLimit adds v to the "key_soft_limit" field.
func (u *SubPoolUpsertBulk) AddKeySoftLimit(v int) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddKeySoftLimit(v)
	})
}

// UpdateKeySoftLimit sets the "key_soft_limit" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateKeySoftLimit() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateKeySoftLimit()
	})
}

// SetCoolingUntil sets the "cooling_until" field.
func (u *SubPoolUpsertBulk) SetCoolingUntil(v time.Time) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetCoolingUntil(v)
	})
}

// UpdateCoolingUntil sets the "cooling_until" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateCoolingUntil() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateCoolingUntil()
	})
}

// ClearCoolingUntil clears the value of the "cooling_until" field.
func (u *SubPoolUpsertBulk) ClearCoolingUntil() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearCoolingUntil()
	})
}

// SetCoolingReason sets the "cooling_reason" field.
func (u *SubPoolUpsertBulk) SetCoolingReason(v string) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetCoolingReason(v)
	})
}

// UpdateCoolingReason sets the "cooling_reason" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateCoolingReason() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateCoolingReason()
	})
}

// ClearCoolingReason clears the value of the "cooling_reason" field.
func (u *SubPoolUpsertBulk) ClearCoolingReason() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.ClearCoolingReason()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *SubPoolUpsertBulk) SetSortOrder(v int) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *SubPoolUpsertBulk) AddSortOrder(v int) *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *SubPoolUpsertBulk) UpdateSortOrder() *SubPoolUpsertBulk {
	return u.Update(func(s *SubPoolUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *SubPoolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubPoolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubPoolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubPoolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
