// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
	"github.com/Wei-Shaw/sub2api/ent/subpoolaccount"
)

// SubPoolAccountCreate is the builder for creating a SubPoolAccount entity.
type SubPoolAccountCreate struct {
	config
	mutation *SubPoolAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubPoolID sets the "sub_pool_id" field.
func (_c *SubPoolAccountCreate) SetSubPoolID(v int64) *SubPoolAccountCreate {
	_c.mutation.SetSubPoolID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *SubPoolAccountCreate) SetAccountID(v int64) *SubPoolAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubPoolAccountCreate) SetGroupID(v int64) *SubPoolAccountCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *SubPoolAccountCreate) SetRole(v string) *SubPoolAccountCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *SubPoolAccountCreate) SetNillableRole(v *string) *SubPoolAccountCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubPoolAccountCreate) SetCreatedAt(v time.Time) *SubPoolAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubPoolAccountCreate) SetNillableCreatedAt(v *time.Time) *SubPoolAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSubPool sets the "sub_pool" edge to the SubPool entity.
func (_c *SubPoolAccountCreate) SetSubPool(v *SubPool) *SubPoolAccountCreate {
	return _c.SetSubPoolID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *SubPoolAccountCreate) SetAccount(v *Account) *SubPoolAccountCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the SubPoolAccountMutation object of the builder.
func (_c *SubPoolAccountCreate) Mutation() *SubPoolAccountMutation {
	return _c.mutation
}

// Save creates the SubPoolAccount in the database.
func (_c *SubPoolAccountCreate) Save(ctx context.Context) (*SubPoolAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubPoolAccountCreate) SaveX(ctx context.Context) *SubPoolAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubPoolAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubPoolAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubPoolAccountCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := subpoolaccount.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subpoolaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubPoolAccountCreate) check() error {
	if _, ok := _c.mutation.SubPoolID(); !ok {
		return &ValidationError{Name: "sub_pool_id", err: errors.New(`ent: missing required field "SubPoolAccount.sub_pool_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "SubPoolAccount.account_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubPoolAccount.group_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "SubPoolAccount.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := subpoolaccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SubPoolAccount.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubPoolAccount.created_at"`)}
	}
	if len(_c.mutation.SubPoolIDs()) == 0 {
		return &ValidationError{Name: "sub_pool", err: errors.New(`ent: missing required edge "SubPoolAccount.sub_pool"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "SubPoolAccount.account"`)}
	}
	return nil
}

func (_c *SubPoolAccountCreate) sqlSave(ctx context.Context) (*SubPoolAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *SubPoolAccountCreate) createSpec() (*SubPoolAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &SubPoolAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subpoolaccount.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(subpoolaccount.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(subpoolaccount.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subpoolaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SubPoolIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.SubPoolTable,
			Columns: []string{subpoolaccount.SubPoolColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubPoolID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subpoolaccount.AccountTable,
			Columns: []string{subpoolaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubPoolAccount.Create().
//		SetSubPoolID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubPoolAccountUpsert) {
//			SetSubPoolID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubPoolAccountCreate) OnConflict(opts ...sql.ConflictOption) *SubPoolAccountUpsertOne {
	_c.conflict = opts
	return &SubPoolAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubPoolAccountCreate) OnConflictColumns(columns ...string) *SubPoolAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubPoolAccountUpsertOne{
		create: _c,
	}
}

type (
	// SubPoolAccountUpsertOne is the builder for "upsert"-ing
	//  one SubPoolAccount node.
	SubPoolAccountUpsertOne struct {
		create *SubPoolAccountCreate
	}

	// SubPoolAccountUpsert is the "OnConflict" setter.
	SubPoolAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubPoolID sets the "sub_pool_id" field.
func (u *SubPoolAccountUpsert) SetSubPoolID(v int64) *SubPoolAccountUpsert {
	u.Set(subpoolaccount.FieldSubPoolID, v)
	return u
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsert) UpdateSubPoolID() *SubPoolAccountUpsert {
	u.SetExcluded(subpoolaccount.FieldSubPoolID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *SubPoolAccountUpsert) SetAccountID(v int64) *SubPoolAccountUpsert {
	u.Set(subpoolaccount.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsert) UpdateAccountID() *SubPoolAccountUpsert {
	u.SetExcluded(subpoolaccount.FieldAccountID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolAccountUpsert) SetGroupID(v int64) *SubPoolAccountUpsert {
	u.Set(subpoolaccount.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsert) UpdateGroupID() *SubPoolAccountUpsert {
	u.SetExcluded(subpoolaccount.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolAccountUpsert) AddGroupID(v int64) *SubPoolAccountUpsert {
	u.Add(subpoolaccount.FieldGroupID, v)
	return u
}

// SetRole sets the "role" field.
func (u *SubPoolAccountUpsert) SetRole(v string) *SubPoolAccountUpsert {
	u.Set(subpoolaccount.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SubPoolAccountUpsert) UpdateRole() *SubPoolAccountUpsert {
	u.SetExcluded(subpoolaccount.FieldRole)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubPoolAccountUpsertOne) UpdateNewValues() *SubPoolAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subpoolaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubPoolAccountUpsertOne) Ignore() *SubPoolAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubPoolAccountUpsertOne) DoNothing() *SubPoolAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubPoolAccountCreate.OnConflict
// documentation for more info.
func (u *SubPoolAccountUpsertOne) Update(set func(*SubPoolAccountUpsert)) *SubPoolAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubPoolAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (u *SubPoolAccountUpsertOne) SetSubPoolID(v int64) *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetSubPoolID(v)
	})
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertOne) UpdateSubPoolID() *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateSubPoolID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SubPoolAccountUpsertOne) SetAccountID(v int64) *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertOne) UpdateAccountID() *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolAccountUpsertOne) SetGroupID(v int64) *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolAccountUpsertOne) AddGroupID(v int64) *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertOne) UpdateGroupID() *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateGroupID()
	})
}

// SetRole sets the "role" field.
func (u *SubPoolAccountUpsertOne) SetRole(v string) *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SubPoolAccountUpsertOne) UpdateRole() *SubPoolAccountUpsertOne {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *SubPoolAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubPoolAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubPoolAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// SubPoolAccountCreateBulk is the builder for creating many SubPoolAccount entities in bulk.
type SubPoolAccountCreateBulk struct {
	config
	err      error
	builders []*SubPoolAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the SubPoolAccount entities in the database.
func (_c *SubPoolAccountCreateBulk) Save(ctx context.Context) ([]*SubPoolAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubPoolAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubPoolAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubPoolAccountCreateBulk) SaveX(ctx context.Context) []*SubPoolAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubPoolAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubPoolAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubPoolAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubPoolAccountUpsert) {
//			SetSubPoolID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubPoolAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubPoolAccountUpsertBulk {
	_c.conflict = opts
	return &SubPoolAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubPoolAccountCreateBulk) OnConflictColumns(columns ...string) *SubPoolAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubPoolAccountUpsertBulk{
		create: _c,
	}
}

// SubPoolAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of SubPoolAccount nodes.
type SubPoolAccountUpsertBulk struct {
	create *SubPoolAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubPoolAccountUpsertBulk) UpdateNewValues() *SubPoolAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subpoolaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubPoolAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubPoolAccountUpsertBulk) Ignore() *SubPoolAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubPoolAccountUpsertBulk) DoNothing() *SubPoolAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubPoolAccountCreateBulk.OnConflict
// documentation for more info.
func (u *SubPoolAccountUpsertBulk) Update(set func(*SubPoolAccountUpsert)) *SubPoolAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubPoolAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubPoolID sets the "sub_pool_id" field.
func (u *SubPoolAccountUpsertBulk) SetSubPoolID(v int64) *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetSubPoolID(v)
	})
}

// UpdateSubPoolID sets the "sub_pool_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertBulk) UpdateSubPoolID() *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateSubPoolID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SubPoolAccountUpsertBulk) SetAccountID(v int64) *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertBulk) UpdateAccountID() *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubPoolAccountUpsertBulk) SetGroupID(v int64) *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubPoolAccountUpsertBulk) AddGroupID(v int64) *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubPoolAccountUpsertBulk) UpdateGroupID() *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateGroupID()
	})
}

// SetRole sets the "role" field.
func (u *SubPoolAccountUpsertBulk) SetRole(v string) *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *SubPoolAccountUpsertBulk) UpdateRole() *SubPoolAccountUpsertBulk {
	return u.Update(func(s *SubPoolAccountUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *SubPoolAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubPoolAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubPoolAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubPoolAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
