// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
	"github.com/Wei-Shaw/sub2api/ent/subpoolaccount"
)

// SubPoolAccount is the model entity for the SubPoolAccount schema.
type SubPoolAccount struct {
	config `json:"-"`
	// SubPoolID holds the value of the "sub_pool_id" field.
	SubPoolID int64 `json:"sub_pool_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// primary | standby
	Role string `json:"role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubPoolAccountQuery when eager-loading is set.
	Edges        SubPoolAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubPoolAccountEdges holds the relations/edges for other nodes in the graph.
type SubPoolAccountEdges struct {
	// SubPool holds the value of the sub_pool edge.
	SubPool *SubPool `json:"sub_pool,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SubPoolOrErr returns the SubPool value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubPoolAccountEdges) SubPoolOrErr() (*SubPool, error) {
	if e.SubPool != nil {
		return e.SubPool, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subpool.Label}
	}
	return nil, &NotLoadedError{edge: "sub_pool"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubPoolAccountEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubPoolAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subpoolaccount.FieldSubPoolID, subpoolaccount.FieldAccountID, subpoolaccount.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case subpoolaccount.FieldRole:
			values[i] = new(sql.NullString)
		case subpoolaccount.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubPoolAccount fields.
func (_m *SubPoolAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subpoolaccount.FieldSubPoolID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_pool_id", values[i])
			} else if value.Valid {
				_m.SubPoolID = value.Int64
			}
		case subpoolaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case subpoolaccount.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subpoolaccount.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case subpoolaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubPoolAccount.
// This includes values selected through modifiers, order, etc.
func (_m *SubPoolAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubPool queries the "sub_pool" edge of the SubPoolAccount entity.
func (_m *SubPoolAccount) QuerySubPool() *SubPoolQuery {
	return NewSubPoolAccountClient(_m.config).QuerySubPool(_m)
}

// QueryAccount queries the "account" edge of the SubPoolAccount entity.
func (_m *SubPoolAccount) QueryAccount() *AccountQuery {
	return NewSubPoolAccountClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this SubPoolAccount.
// Note that you need to call SubPoolAccount.Unwrap() before calling this method if this SubPoolAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubPoolAccount) Update() *SubPoolAccountUpdateOne {
	return NewSubPoolAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubPoolAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubPoolAccount) Unwrap() *SubPoolAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubPoolAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubPoolAccount) String() string {
	var builder strings.Builder
	builder.WriteString("SubPoolAccount(")
	builder.WriteString("sub_pool_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubPoolID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubPoolAccounts is a parsable slice of SubPoolAccount.
type SubPoolAccounts []*SubPoolAccount
