// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subpool"
	"github.com/Wei-Shaw/sub2api/ent/subpoolaccount"
)

// SubPoolQuery is the builder for querying SubPool entities.
type SubPoolQuery struct {
	config
	ctx                 *QueryContext
	order               []subpool.OrderOption
	inters              []Interceptor
	predicates          []predicate.SubPool
	withAPIKeys         *APIKeyQuery
	withAccounts        *AccountQuery
	withSubPoolAccounts *SubPoolAccountQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubPoolQuery builder.
func (_q *SubPoolQuery) Where(ps ...predicate.SubPool) *SubPoolQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubPoolQuery) Limit(limit int) *SubPoolQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubPoolQuery) Offset(offset int) *SubPoolQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubPoolQuery) Unique(unique bool) *SubPoolQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubPoolQuery) Order(o ...subpool.OrderOption) *SubPoolQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAPIKeys chains the current query on the "api_keys" edge.
func (_q *SubPoolQuery) QueryAPIKeys() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subpool.Table, subpool.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subpool.APIKeysTable, subpool.APIKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccounts chains the current query on the "accounts" edge.
func (_q *SubPoolQuery) QueryAccounts() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subpool.Table, subpool.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, subpool.AccountsTable, subpool.AccountsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubPoolAccounts chains the current query on the "sub_pool_accounts" edge.
func (_q *SubPoolQuery) QuerySubPoolAccounts() *SubPoolAccountQuery {
	query := (&SubPoolAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subpool.Table, subpool.FieldID, selector),
			sqlgraph.To(subpoolaccount.Table, subpoolaccount.SubPoolColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, subpool.SubPoolAccountsTable, subpool.SubPoolAccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubPool entity from the query.
// Returns a *NotFoundError when no SubPool was found.
func (_q *SubPoolQuery) First(ctx context.Context) (*SubPool, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subpool.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubPoolQuery) FirstX(ctx context.Context) *SubPool {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubPool ID from the query.
// Returns a *NotFoundError when no SubPool ID was found.
func (_q *SubPoolQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subpool.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubPoolQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubPool entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubPool entity is found.
// Returns a *NotFoundError when no SubPool entities are found.
func (_q *SubPoolQuery) Only(ctx context.Context) (*SubPool, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subpool.Label}
	default:
		return nil, &NotSingularError{subpool.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubPoolQuery) OnlyX(ctx context.Context) *SubPool {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubPool ID in the query.
// Returns a *NotSingularError when more than one SubPool ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubPoolQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subpool.Label}
	default:
		err = &NotSingularError{subpool.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubPoolQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubPools.
func (_q *SubPoolQuery) All(ctx context.Context) ([]*SubPool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubPool, *SubPoolQuery]()
	return withInterceptors[[]*SubPool](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubPoolQuery) AllX(ctx context.Context) []*SubPool {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubPool IDs.
func (_q *SubPoolQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subpool.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubPoolQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubPoolQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubPoolQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubPoolQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubPoolQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubPoolQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubPoolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubPoolQuery) Clone() *SubPoolQuery {
	if _q == nil {
		return nil
	}
	return &SubPoolQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]subpool.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.SubPool{}, _q.predicates...),
		withAPIKeys:         _q.withAPIKeys.Clone(),
		withAccounts:        _q.withAccounts.Clone(),
		withSubPoolAccounts: _q.withSubPoolAccounts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAPIKeys tells the query-builder to eager-load the nodes that are connected to
// the "api_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubPoolQuery) WithAPIKeys(opts ...func(*APIKeyQuery)) *SubPoolQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKeys = query
	return _q
}

// WithAccounts tells the query-builder to eager-load the nodes that are connected to
// the "accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubPoolQuery) WithAccounts(opts ...func(*AccountQuery)) *SubPoolQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccounts = query
	return _q
}

// WithSubPoolAccounts tells the query-builder to eager-load the nodes that are connected to
// the "sub_pool_accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubPoolQuery) WithSubPoolAccounts(opts ...func(*SubPoolAccountQuery)) *SubPoolQuery {
	query := (&SubPoolAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubPoolAccounts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubPool.Query().
//		GroupBy(subpool.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubPoolQuery) GroupBy(field string, fields ...string) *SubPoolGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubPoolGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subpool.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SubPool.Query().
//		Select(subpool.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SubPoolQuery) Select(fields ...string) *SubPoolSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubPoolSelect{SubPoolQuery: _q}
	sbuild.label = subpool.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubPoolSelect configured with the given aggregations.
func (_q *SubPoolQuery) Aggregate(fns ...AggregateFunc) *SubPoolSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubPoolQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subpool.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubPoolQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubPool, error) {
	var (
		nodes       = []*SubPool{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withAPIKeys != nil,
			_q.withAccounts != nil,
			_q.withSubPoolAccounts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubPool).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubPool{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAPIKeys; query != nil {
		if err := _q.loadAPIKeys(ctx, query, nodes,
			func(n *SubPool) { n.Edges.APIKeys = []*APIKey{} },
			func(n *SubPool, e *APIKey) { n.Edges.APIKeys = append(n.Edges.APIKeys, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAccounts; query != nil {
		if err := _q.loadAccounts(ctx, query, nodes,
			func(n *SubPool) { n.Edges.Accounts = []*Account{} },
			func(n *SubPool, e *Account) { n.Edges.Accounts = append(n.Edges.Accounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubPoolAccounts; query != nil {
		if err := _q.loadSubPoolAccounts(ctx, query, nodes,
			func(n *SubPool) { n.Edges.SubPoolAccounts = []*SubPoolAccount{} },
			func(n *SubPool, e *SubPoolAccount) { n.Edges.SubPoolAccounts = append(n.Edges.SubPoolAccounts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubPoolQuery) loadAPIKeys(ctx context.Context, query *APIKeyQuery, nodes []*SubPool, init func(*SubPool), assign func(*SubPool, *APIKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(apikey.FieldSubPoolID)
	}
	query.Where(predicate.APIKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subpool.APIKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SubPoolID
		if fk == nil {
			return fmt.Errorf(`foreign-key "sub_pool_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sub_pool_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SubPoolQuery) loadAccounts(ctx context.Context, query *AccountQuery, nodes []*SubPool, init func(*SubPool), assign func(*SubPool, *Account)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*SubPool)
	nids := make(map[int64]map[*SubPool]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(subpool.AccountsTable)
		s.Join(joinT).On(s.C(account.FieldID), joinT.C(subpool.AccountsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(subpool.AccountsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(subpool.AccountsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*SubPool]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Account](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "accounts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SubPoolQuery) loadSubPoolAccounts(ctx context.Context, query *SubPoolAccountQuery, nodes []*SubPool, init func(*SubPool), assign func(*SubPool, *SubPoolAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubPool)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(subpoolaccount.FieldSubPoolID)
	}
	query.Where(predicate.SubPoolAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subpool.SubPoolAccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SubPoolID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sub_pool_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubPoolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubPoolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subpool.Table, subpool.Columns, sqlgraph.NewFieldSpec(subpool.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subpool.FieldID)
		for i := range fields {
			if fields[i] != subpool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubPoolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subpool.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subpool.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubPoolQuery) ForUpdate(opts ...sql.LockOption) *SubPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubPoolQuery) ForShare(opts ...sql.LockOption) *SubPoolQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubPoolGroupBy is the group-by builder for SubPool entities.
type SubPoolGroupBy struct {
	selector
	build *SubPoolQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubPoolGroupBy) Aggregate(fns ...AggregateFunc) *SubPoolGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubPoolGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubPoolQuery, *SubPoolGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubPoolGroupBy) sqlScan(ctx context.Context, root *SubPoolQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubPoolSelect is the builder for selecting fields of SubPool entities.
type SubPoolSelect struct {
	*SubPoolQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubPoolSelect) Aggregate(fns ...AggregateFunc) *SubPoolSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubPoolSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubPoolQuery, *SubPoolSelect](ctx, _s.SubPoolQuery, _s, _s.inters, v)
}

func (_s *SubPoolSelect) sqlScan(ctx context.Context, root *SubPoolQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
