// Code generated by ent, DO NOT EDIT.

package subpool

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldDeletedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldGroupID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldDescription, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldKind, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldStatus, v))
}

// KeySoftLimit applies equality check predicate on the "key_soft_limit" field. It's identical to KeySoftLimitEQ.
func KeySoftLimit(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldKeySoftLimit, v))
}

// CoolingUntil applies equality check predicate on the "cooling_until" field. It's identical to CoolingUntilEQ.
func CoolingUntil(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCoolingUntil, v))
}

// CoolingReason applies equality check predicate on the "cooling_reason" field. It's identical to CoolingReasonEQ.
func CoolingReason(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCoolingReason, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldNotNull(FieldDeletedAt))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldGroupID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContainsFold(FieldDescription, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContainsFold(FieldKind, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContainsFold(FieldStatus, v))
}

// KeySoftLimitEQ applies the EQ predicate on the "key_soft_limit" field.
func KeySoftLimitEQ(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldKeySoftLimit, v))
}

// KeySoftLimitNEQ applies the NEQ predicate on the "key_soft_limit" field.
func KeySoftLimitNEQ(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldKeySoftLimit, v))
}

// KeySoftLimitIn applies the In predicate on the "key_soft_limit" field.
func KeySoftLimitIn(vs ...int) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldKeySoftLimit, vs...))
}

// KeySoftLimitNotIn applies the NotIn predicate on the "key_soft_limit" field.
func KeySoftLimitNotIn(vs ...int) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldKeySoftLimit, vs...))
}

// KeySoftLimitGT applies the GT predicate on the "key_soft_limit" field.
func KeySoftLimitGT(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldKeySoftLimit, v))
}

// KeySoftLimitGTE applies the GTE predicate on the "key_soft_limit" field.
func KeySoftLimitGTE(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldKeySoftLimit, v))
}

// KeySoftLimitLT applies the LT predicate on the "key_soft_limit" field.
func KeySoftLimitLT(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldKeySoftLimit, v))
}

// KeySoftLimitLTE applies the LTE predicate on the "key_soft_limit" field.
func KeySoftLimitLTE(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldKeySoftLimit, v))
}

// CoolingUntilEQ applies the EQ predicate on the "cooling_until" field.
func CoolingUntilEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCoolingUntil, v))
}

// CoolingUntilNEQ applies the NEQ predicate on the "cooling_until" field.
func CoolingUntilNEQ(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldCoolingUntil, v))
}

// CoolingUntilIn applies the In predicate on the "cooling_until" field.
func CoolingUntilIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldCoolingUntil, vs...))
}

// CoolingUntilNotIn applies the NotIn predicate on the "cooling_until" field.
func CoolingUntilNotIn(vs ...time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldCoolingUntil, vs...))
}

// CoolingUntilGT applies the GT predicate on the "cooling_until" field.
func CoolingUntilGT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldCoolingUntil, v))
}

// CoolingUntilGTE applies the GTE predicate on the "cooling_until" field.
func CoolingUntilGTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldCoolingUntil, v))
}

// CoolingUntilLT applies the LT predicate on the "cooling_until" field.
func CoolingUntilLT(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldCoolingUntil, v))
}

// CoolingUntilLTE applies the LTE predicate on the "cooling_until" field.
func CoolingUntilLTE(v time.Time) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldCoolingUntil, v))
}

// CoolingUntilIsNil applies the IsNil predicate on the "cooling_until" field.
func CoolingUntilIsNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldIsNull(FieldCoolingUntil))
}

// CoolingUntilNotNil applies the NotNil predicate on the "cooling_until" field.
func CoolingUntilNotNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldNotNull(FieldCoolingUntil))
}

// CoolingReasonEQ applies the EQ predicate on the "cooling_reason" field.
func CoolingReasonEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldCoolingReason, v))
}

// CoolingReasonNEQ applies the NEQ predicate on the "cooling_reason" field.
func CoolingReasonNEQ(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldCoolingReason, v))
}

// CoolingReasonIn applies the In predicate on the "cooling_reason" field.
func CoolingReasonIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldCoolingReason, vs...))
}

// CoolingReasonNotIn applies the NotIn predicate on the "cooling_reason" field.
func CoolingReasonNotIn(vs ...string) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldCoolingReason, vs...))
}

// CoolingReasonGT applies the GT predicate on the "cooling_reason" field.
func CoolingReasonGT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldCoolingReason, v))
}

// CoolingReasonGTE applies the GTE predicate on the "cooling_reason" field.
func CoolingReasonGTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldCoolingReason, v))
}

// CoolingReasonLT applies the LT predicate on the "cooling_reason" field.
func CoolingReasonLT(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldCoolingReason, v))
}

// CoolingReasonLTE applies the LTE predicate on the "cooling_reason" field.
func CoolingReasonLTE(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldCoolingReason, v))
}

// CoolingReasonContains applies the Contains predicate on the "cooling_reason" field.
func CoolingReasonContains(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContains(FieldCoolingReason, v))
}

// CoolingReasonHasPrefix applies the HasPrefix predicate on the "cooling_reason" field.
func CoolingReasonHasPrefix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasPrefix(FieldCoolingReason, v))
}

// CoolingReasonHasSuffix applies the HasSuffix predicate on the "cooling_reason" field.
func CoolingReasonHasSuffix(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldHasSuffix(FieldCoolingReason, v))
}

// CoolingReasonIsNil applies the IsNil predicate on the "cooling_reason" field.
func CoolingReasonIsNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldIsNull(FieldCoolingReason))
}

// CoolingReasonNotNil applies the NotNil predicate on the "cooling_reason" field.
func CoolingReasonNotNil() predicate.SubPool {
	return predicate.SubPool(sql.FieldNotNull(FieldCoolingReason))
}

// CoolingReasonEqualFold applies the EqualFold predicate on the "cooling_reason" field.
func CoolingReasonEqualFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldEqualFold(FieldCoolingReason, v))
}

// CoolingReasonContainsFold applies the ContainsFold predicate on the "cooling_reason" field.
func CoolingReasonContainsFold(v string) predicate.SubPool {
	return predicate.SubPool(sql.FieldContainsFold(FieldCoolingReason, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.SubPool {
	return predicate.SubPool(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.SubPool {
	return predicate.SubPool(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.SubPool {
	return predicate.SubPool(sql.FieldLTE(FieldSortOrder, v))
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AccountsTable, AccountsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubPoolAccounts applies the HasEdge predicate on the "sub_pool_accounts" edge.
func HasSubPoolAccounts() predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, SubPoolAccountsTable, SubPoolAccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubPoolAccountsWith applies the HasEdge predicate on the "sub_pool_accounts" edge with a given conditions (other predicates).
func HasSubPoolAccountsWith(preds ...predicate.SubPoolAccount) predicate.SubPool {
	return predicate.SubPool(func(s *sql.Selector) {
		step := newSubPoolAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubPool) predicate.SubPool {
	return predicate.SubPool(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubPool) predicate.SubPool {
	return predicate.SubPool(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubPool) predicate.SubPool {
	return predicate.SubPool(sql.NotPredicates(p))
}
