// Code generated by ent, DO NOT EDIT.

package subpoolaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subpoolaccount type in the database.
	Label = "sub_pool_account"
	// FieldSubPoolID holds the string denoting the sub_pool_id field in the database.
	FieldSubPoolID = "sub_pool_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSubPool holds the string denoting the sub_pool edge name in mutations.
	EdgeSubPool = "sub_pool"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// SubPoolFieldID holds the string denoting the ID field of the SubPool.
	SubPoolFieldID = "id"
	// AccountFieldID holds the string denoting the ID field of the Account.
	AccountFieldID = "id"
	// Table holds the table name of the subpoolaccount in the database.
	Table = "sub_pool_accounts"
	// SubPoolTable is the table that holds the sub_pool relation/edge.
	SubPoolTable = "sub_pool_accounts"
	// SubPoolInverseTable is the table name for the SubPool entity.
	// It exists in this package in order to avoid circular dependency with the "subpool" package.
	SubPoolInverseTable = "sub_pools"
	// SubPoolColumn is the table column denoting the sub_pool relation/edge.
	SubPoolColumn = "sub_pool_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "sub_pool_accounts"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for subpoolaccount fields.
var Columns = []string{
	FieldSubPoolID,
	FieldAccountID,
	FieldGroupID,
	FieldRole,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubPoolAccount queries.
type OrderOption func(*sql.Selector)

// BySubPoolID orders the results by the sub_pool_id field.
func BySubPoolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubPoolID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySubPoolField orders the results by sub_pool field.
func BySubPoolField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubPoolStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newSubPoolStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, SubPoolColumn),
		sqlgraph.To(SubPoolInverseTable, SubPoolFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SubPoolTable, SubPoolColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, AccountColumn),
		sqlgraph.To(AccountInverseTable, AccountFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
