// Code generated by ent, DO NOT EDIT.

package subpoolaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// SubPoolID applies equality check predicate on the "sub_pool_id" field. It's identical to SubPoolIDEQ.
func SubPoolID(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldSubPoolID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldGroupID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldRole, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// SubPoolIDEQ applies the EQ predicate on the "sub_pool_id" field.
func SubPoolIDEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldSubPoolID, v))
}

// SubPoolIDNEQ applies the NEQ predicate on the "sub_pool_id" field.
func SubPoolIDNEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNEQ(FieldSubPoolID, v))
}

// SubPoolIDIn applies the In predicate on the "sub_pool_id" field.
func SubPoolIDIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldIn(FieldSubPoolID, vs...))
}

// SubPoolIDNotIn applies the NotIn predicate on the "sub_pool_id" field.
func SubPoolIDNotIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNotIn(FieldSubPoolID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLTE(FieldGroupID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldContainsFold(FieldRole, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSubPool applies the HasEdge predicate on the "sub_pool" edge.
func HasSubPool() predicate.SubPoolAccount {
	return predicate.SubPoolAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, SubPoolColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, SubPoolTable, SubPoolColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubPoolWith applies the HasEdge predicate on the "sub_pool" edge with a given conditions (other predicates).
func HasSubPoolWith(preds ...predicate.SubPool) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(func(s *sql.Selector) {
		step := newSubPoolStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.SubPoolAccount {
	return predicate.SubPoolAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, AccountColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubPoolAccount) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubPoolAccount) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubPoolAccount) predicate.SubPoolAccount {
	return predicate.SubPoolAccount(sql.NotPredicates(p))
}
