// Code generated by ent, DO NOT EDIT.

package apikeyreputation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the apikeyreputation type in the database.
	Label = "api_key_reputation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldSevereHits holds the string denoting the severe_hits field in the database.
	FieldSevereHits = "severe_hits"
	// FieldTotalHits holds the string denoting the total_hits field in the database.
	FieldTotalHits = "total_hits"
	// FieldLastEventAt holds the string denoting the last_event_at field in the database.
	FieldLastEventAt = "last_event_at"
	// FieldScoredAt holds the string denoting the scored_at field in the database.
	FieldScoredAt = "scored_at"
	// FieldSanction holds the string denoting the sanction field in the database.
	FieldSanction = "sanction"
	// FieldSanctionedAt holds the string denoting the sanctioned_at field in the database.
	FieldSanctionedAt = "sanctioned_at"
	// FieldSanctionReason holds the string denoting the sanction_reason field in the database.
	FieldSanctionReason = "sanction_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the apikeyreputation in the database.
	Table = "api_key_reputation"
)

// Columns holds all SQL columns for apikeyreputation fields.
var Columns = []string{
	FieldID,
	FieldAPIKeyID,
	FieldScore,
	FieldSevereHits,
	FieldTotalHits,
	FieldLastEventAt,
	FieldScoredAt,
	FieldSanction,
	FieldSanctionedAt,
	FieldSanctionReason,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore int
	// DefaultSevereHits holds the default value on creation for the "severe_hits" field.
	DefaultSevereHits int
	// DefaultTotalHits holds the default value on creation for the "total_hits" field.
	DefaultTotalHits int
	// DefaultScoredAt holds the default value on creation for the "scored_at" field.
	DefaultScoredAt func() time.Time
	// DefaultSanction holds the default value on creation for the "sanction" field.
	DefaultSanction string
	// SanctionValidator is a validator for the "sanction" field. It is called by the builders before save.
	SanctionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the APIKeyReputation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// BySevereHits orders the results by the severe_hits field.
func BySevereHits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSevereHits, opts...).ToFunc()
}

// ByTotalHits orders the results by the total_hits field.
func ByTotalHits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalHits, opts...).ToFunc()
}

// ByLastEventAt orders the results by the last_event_at field.
func ByLastEventAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEventAt, opts...).ToFunc()
}

// ByScoredAt orders the results by the scored_at field.
func ByScoredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoredAt, opts...).ToFunc()
}

// BySanction orders the results by the sanction field.
func BySanction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSanction, opts...).ToFunc()
}

// BySanctionedAt orders the results by the sanctioned_at field.
func BySanctionedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSanctionedAt, opts...).ToFunc()
}

// BySanctionReason orders the results by the sanction_reason field.
func BySanctionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSanctionReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
