// Code generated by ent, DO NOT EDIT.

package apikeyreputation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldID, id))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldAPIKeyID, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldScore, v))
}

// SevereHits applies equality check predicate on the "severe_hits" field. It's identical to SevereHitsEQ.
func SevereHits(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSevereHits, v))
}

// TotalHits applies equality check predicate on the "total_hits" field. It's identical to TotalHitsEQ.
func TotalHits(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldTotalHits, v))
}

// LastEventAt applies equality check predicate on the "last_event_at" field. It's identical to LastEventAtEQ.
func LastEventAt(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldLastEventAt, v))
}

// ScoredAt applies equality check predicate on the "scored_at" field. It's identical to ScoredAtEQ.
func ScoredAt(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldScoredAt, v))
}

// Sanction applies equality check predicate on the "sanction" field. It's identical to SanctionEQ.
func Sanction(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanction, v))
}

// SanctionedAt applies equality check predicate on the "sanctioned_at" field. It's identical to SanctionedAtEQ.
func SanctionedAt(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanctionedAt, v))
}

// SanctionReason applies equality check predicate on the "sanction_reason" field. It's identical to SanctionReasonEQ.
func SanctionReason(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanctionReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldAPIKeyID, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldScore, v))
}

// SevereHitsEQ applies the EQ predicate on the "severe_hits" field.
func SevereHitsEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSevereHits, v))
}

// SevereHitsNEQ applies the NEQ predicate on the "severe_hits" field.
func SevereHitsNEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldSevereHits, v))
}

// SevereHitsIn applies the In predicate on the "severe_hits" field.
func SevereHitsIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldSevereHits, vs...))
}

// SevereHitsNotIn applies the NotIn predicate on the "severe_hits" field.
func SevereHitsNotIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldSevereHits, vs...))
}

// SevereHitsGT applies the GT predicate on the "severe_hits" field.
func SevereHitsGT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldSevereHits, v))
}

// SevereHitsGTE applies the GTE predicate on the "severe_hits" field.
func SevereHitsGTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldSevereHits, v))
}

// SevereHitsLT applies the LT predicate on the "severe_hits" field.
func SevereHitsLT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldSevereHits, v))
}

// SevereHitsLTE applies the LTE predicate on the "severe_hits" field.
func SevereHitsLTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldSevereHits, v))
}

// TotalHitsEQ applies the EQ predicate on the "total_hits" field.
func TotalHitsEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldTotalHits, v))
}

// TotalHitsNEQ applies the NEQ predicate on the "total_hits" field.
func TotalHitsNEQ(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldTotalHits, v))
}

// TotalHitsIn applies the In predicate on the "total_hits" field.
func TotalHitsIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldTotalHits, vs...))
}

// TotalHitsNotIn applies the NotIn predicate on the "total_hits" field.
func TotalHitsNotIn(vs ...int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldTotalHits, vs...))
}

// TotalHitsGT applies the GT predicate on the "total_hits" field.
func TotalHitsGT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldTotalHits, v))
}

// TotalHitsGTE applies the GTE predicate on the "total_hits" field.
func TotalHitsGTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldTotalHits, v))
}

// TotalHitsLT applies the LT predicate on the "total_hits" field.
func TotalHitsLT(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldTotalHits, v))
}

// TotalHitsLTE applies the LTE predicate on the "total_hits" field.
func TotalHitsLTE(v int) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldTotalHits, v))
}

// LastEventAtEQ applies the EQ predicate on the "last_event_at" field.
func LastEventAtEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldLastEventAt, v))
}

// LastEventAtNEQ applies the NEQ predicate on the "last_event_at" field.
func LastEventAtNEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldLastEventAt, v))
}

// LastEventAtIn applies the In predicate on the "last_event_at" field.
func LastEventAtIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldLastEventAt, vs...))
}

// LastEventAtNotIn applies the NotIn predicate on the "last_event_at" field.
func LastEventAtNotIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldLastEventAt, vs...))
}

// LastEventAtGT applies the GT predicate on the "last_event_at" field.
func LastEventAtGT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldLastEventAt, v))
}

// LastEventAtGTE applies the GTE predicate on the "last_event_at" field.
func LastEventAtGTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldLastEventAt, v))
}

// LastEventAtLT applies the LT predicate on the "last_event_at" field.
func LastEventAtLT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldLastEventAt, v))
}

// LastEventAtLTE applies the LTE predicate on the "last_event_at" field.
func LastEventAtLTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldLastEventAt, v))
}

// LastEventAtIsNil applies the IsNil predicate on the "last_event_at" field.
func LastEventAtIsNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIsNull(FieldLastEventAt))
}

// LastEventAtNotNil applies the NotNil predicate on the "last_event_at" field.
func LastEventAtNotNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotNull(FieldLastEventAt))
}

// ScoredAtEQ applies the EQ predicate on the "scored_at" field.
func ScoredAtEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldScoredAt, v))
}

// ScoredAtNEQ applies the NEQ predicate on the "scored_at" field.
func ScoredAtNEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldScoredAt, v))
}

// ScoredAtIn applies the In predicate on the "scored_at" field.
func ScoredAtIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldScoredAt, vs...))
}

// ScoredAtNotIn applies the NotIn predicate on the "scored_at" field.
func ScoredAtNotIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldScoredAt, vs...))
}

// ScoredAtGT applies the GT predicate on the "scored_at" field.
func ScoredAtGT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldScoredAt, v))
}

// ScoredAtGTE applies the GTE predicate on the "scored_at" field.
func ScoredAtGTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldScoredAt, v))
}

// ScoredAtLT applies the LT predicate on the "scored_at" field.
func ScoredAtLT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldScoredAt, v))
}

// ScoredAtLTE applies the LTE predicate on the "scored_at" field.
func ScoredAtLTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldScoredAt, v))
}

// SanctionEQ applies the EQ predicate on the "sanction" field.
func SanctionEQ(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanction, v))
}

// SanctionNEQ applies the NEQ predicate on the "sanction" field.
func SanctionNEQ(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldSanction, v))
}

// SanctionIn applies the In predicate on the "sanction" field.
func SanctionIn(vs ...string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldSanction, vs...))
}

// SanctionNotIn applies the NotIn predicate on the "sanction" field.
func SanctionNotIn(vs ...string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldSanction, vs...))
}

// SanctionGT applies the GT predicate on the "sanction" field.
func SanctionGT(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldSanction, v))
}

// SanctionGTE applies the GTE predicate on the "sanction" field.
func SanctionGTE(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldSanction, v))
}

// SanctionLT applies the LT predicate on the "sanction" field.
func SanctionLT(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldSanction, v))
}

// SanctionLTE applies the LTE predicate on the "sanction" field.
func SanctionLTE(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldSanction, v))
}

// SanctionContains applies the Contains predicate on the "sanction" field.
func SanctionContains(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldContains(FieldSanction, v))
}

// SanctionHasPrefix applies the HasPrefix predicate on the "sanction" field.
func SanctionHasPrefix(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldHasPrefix(FieldSanction, v))
}

// SanctionHasSuffix applies the HasSuffix predicate on the "sanction" field.
func SanctionHasSuffix(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldHasSuffix(FieldSanction, v))
}

// SanctionEqualFold applies the EqualFold predicate on the "sanction" field.
func SanctionEqualFold(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEqualFold(FieldSanction, v))
}

// SanctionContainsFold applies the ContainsFold predicate on the "sanction" field.
func SanctionContainsFold(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldContainsFold(FieldSanction, v))
}

// SanctionedAtEQ applies the EQ predicate on the "sanctioned_at" field.
func SanctionedAtEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanctionedAt, v))
}

// SanctionedAtNEQ applies the NEQ predicate on the "sanctioned_at" field.
func SanctionedAtNEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldSanctionedAt, v))
}

// SanctionedAtIn applies the In predicate on the "sanctioned_at" field.
func SanctionedAtIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldSanctionedAt, vs...))
}

// SanctionedAtNotIn applies the NotIn predicate on the "sanctioned_at" field.
func SanctionedAtNotIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldSanctionedAt, vs...))
}

// SanctionedAtGT applies the GT predicate on the "sanctioned_at" field.
func SanctionedAtGT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldSanctionedAt, v))
}

// SanctionedAtGTE applies the GTE predicate on the "sanctioned_at" field.
func SanctionedAtGTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldSanctionedAt, v))
}

// SanctionedAtLT applies the LT predicate on the "sanctioned_at" field.
func SanctionedAtLT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldSanctionedAt, v))
}

// SanctionedAtLTE applies the LTE predicate on the "sanctioned_at" field.
func SanctionedAtLTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldSanctionedAt, v))
}

// SanctionedAtIsNil applies the IsNil predicate on the "sanctioned_at" field.
func SanctionedAtIsNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIsNull(FieldSanctionedAt))
}

// SanctionedAtNotNil applies the NotNil predicate on the "sanctioned_at" field.
func SanctionedAtNotNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotNull(FieldSanctionedAt))
}

// SanctionReasonEQ applies the EQ predicate on the "sanction_reason" field.
func SanctionReasonEQ(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldSanctionReason, v))
}

// SanctionReasonNEQ applies the NEQ predicate on the "sanction_reason" field.
func SanctionReasonNEQ(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldSanctionReason, v))
}

// SanctionReasonIn applies the In predicate on the "sanction_reason" field.
func SanctionReasonIn(vs ...string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldSanctionReason, vs...))
}

// SanctionReasonNotIn applies the NotIn predicate on the "sanction_reason" field.
func SanctionReasonNotIn(vs ...string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldSanctionReason, vs...))
}

// SanctionReasonGT applies the GT predicate on the "sanction_reason" field.
func SanctionReasonGT(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldSanctionReason, v))
}

// SanctionReasonGTE applies the GTE predicate on the "sanction_reason" field.
func SanctionReasonGTE(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldSanctionReason, v))
}

// SanctionReasonLT applies the LT predicate on the "sanction_reason" field.
func SanctionReasonLT(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldSanctionReason, v))
}

// SanctionReasonLTE applies the LTE predicate on the "sanction_reason" field.
func SanctionReasonLTE(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldSanctionReason, v))
}

// SanctionReasonContains applies the Contains predicate on the "sanction_reason" field.
func SanctionReasonContains(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldContains(FieldSanctionReason, v))
}

// SanctionReasonHasPrefix applies the HasPrefix predicate on the "sanction_reason" field.
func SanctionReasonHasPrefix(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldHasPrefix(FieldSanctionReason, v))
}

// SanctionReasonHasSuffix applies the HasSuffix predicate on the "sanction_reason" field.
func SanctionReasonHasSuffix(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldHasSuffix(FieldSanctionReason, v))
}

// SanctionReasonIsNil applies the IsNil predicate on the "sanction_reason" field.
func SanctionReasonIsNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIsNull(FieldSanctionReason))
}

// SanctionReasonNotNil applies the NotNil predicate on the "sanction_reason" field.
func SanctionReasonNotNil() predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotNull(FieldSanctionReason))
}

// SanctionReasonEqualFold applies the EqualFold predicate on the "sanction_reason" field.
func SanctionReasonEqualFold(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEqualFold(FieldSanctionReason, v))
}

// SanctionReasonContainsFold applies the ContainsFold predicate on the "sanction_reason" field.
func SanctionReasonContainsFold(v string) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldContainsFold(FieldSanctionReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyReputation) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyReputation) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyReputation) predicate.APIKeyReputation {
	return predicate.APIKeyReputation(sql.NotPredicates(p))
}
