// Code generated by ent, DO NOT EDIT.

package apikeysubpoolbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the apikeysubpoolbinding type in the database.
	Label = "api_key_sub_pool_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldSubPoolID holds the string denoting the sub_pool_id field in the database.
	FieldSubPoolID = "sub_pool_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldBoundAt holds the string denoting the bound_at field in the database.
	FieldBoundAt = "bound_at"
	// FieldUnboundAt holds the string denoting the unbound_at field in the database.
	FieldUnboundAt = "unbound_at"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// Table holds the table name of the apikeysubpoolbinding in the database.
	Table = "api_key_sub_pool_bindings"
)

// Columns holds all SQL columns for apikeysubpoolbinding fields.
var Columns = []string{
	FieldID,
	FieldAPIKeyID,
	FieldSubPoolID,
	FieldGroupID,
	FieldBoundAt,
	FieldUnboundAt,
	FieldReason,
	FieldOperator,
	FieldNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBoundAt holds the default value on creation for the "bound_at" field.
	DefaultBoundAt func() time.Time
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultOperator holds the default value on creation for the "operator" field.
	DefaultOperator string
	// OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	OperatorValidator func(string) error
)

// OrderOption defines the ordering options for the APIKeySubPoolBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// BySubPoolID orders the results by the sub_pool_id field.
func BySubPoolID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubPoolID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByBoundAt orders the results by the bound_at field.
func ByBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAt, opts...).ToFunc()
}

// ByUnboundAt orders the results by the unbound_at field.
func ByUnboundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnboundAt, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}
