// Code generated by ent, DO NOT EDIT.

package apikeysubpoolbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldID, id))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldAPIKeyID, v))
}

// SubPoolID applies equality check predicate on the "sub_pool_id" field. It's identical to SubPoolIDEQ.
func SubPoolID(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldSubPoolID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldGroupID, v))
}

// BoundAt applies equality check predicate on the "bound_at" field. It's identical to BoundAtEQ.
func BoundAt(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldBoundAt, v))
}

// UnboundAt applies equality check predicate on the "unbound_at" field. It's identical to UnboundAtEQ.
func UnboundAt(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldUnboundAt, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldReason, v))
}

// Operator applies equality check predicate on the "operator" field. It's identical to OperatorEQ.
func Operator(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldOperator, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldNote, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldAPIKeyID, v))
}

// SubPoolIDEQ applies the EQ predicate on the "sub_pool_id" field.
func SubPoolIDEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldSubPoolID, v))
}

// SubPoolIDNEQ applies the NEQ predicate on the "sub_pool_id" field.
func SubPoolIDNEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldSubPoolID, v))
}

// SubPoolIDIn applies the In predicate on the "sub_pool_id" field.
func SubPoolIDIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldSubPoolID, vs...))
}

// SubPoolIDNotIn applies the NotIn predicate on the "sub_pool_id" field.
func SubPoolIDNotIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldSubPoolID, vs...))
}

// SubPoolIDGT applies the GT predicate on the "sub_pool_id" field.
func SubPoolIDGT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldSubPoolID, v))
}

// SubPoolIDGTE applies the GTE predicate on the "sub_pool_id" field.
func SubPoolIDGTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldSubPoolID, v))
}

// SubPoolIDLT applies the LT predicate on the "sub_pool_id" field.
func SubPoolIDLT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldSubPoolID, v))
}

// SubPoolIDLTE applies the LTE predicate on the "sub_pool_id" field.
func SubPoolIDLTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldSubPoolID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldGroupID, v))
}

// BoundAtEQ applies the EQ predicate on the "bound_at" field.
func BoundAtEQ(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldBoundAt, v))
}

// BoundAtNEQ applies the NEQ predicate on the "bound_at" field.
func BoundAtNEQ(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldBoundAt, v))
}

// BoundAtIn applies the In predicate on the "bound_at" field.
func BoundAtIn(vs ...time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldBoundAt, vs...))
}

// BoundAtNotIn applies the NotIn predicate on the "bound_at" field.
func BoundAtNotIn(vs ...time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldBoundAt, vs...))
}

// BoundAtGT applies the GT predicate on the "bound_at" field.
func BoundAtGT(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldBoundAt, v))
}

// BoundAtGTE applies the GTE predicate on the "bound_at" field.
func BoundAtGTE(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldBoundAt, v))
}

// BoundAtLT applies the LT predicate on the "bound_at" field.
func BoundAtLT(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldBoundAt, v))
}

// BoundAtLTE applies the LTE predicate on the "bound_at" field.
func BoundAtLTE(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldBoundAt, v))
}

// UnboundAtEQ applies the EQ predicate on the "unbound_at" field.
func UnboundAtEQ(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldUnboundAt, v))
}

// UnboundAtNEQ applies the NEQ predicate on the "unbound_at" field.
func UnboundAtNEQ(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldUnboundAt, v))
}

// UnboundAtIn applies the In predicate on the "unbound_at" field.
func UnboundAtIn(vs ...time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldUnboundAt, vs...))
}

// UnboundAtNotIn applies the NotIn predicate on the "unbound_at" field.
func UnboundAtNotIn(vs ...time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldUnboundAt, vs...))
}

// UnboundAtGT applies the GT predicate on the "unbound_at" field.
func UnboundAtGT(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldUnboundAt, v))
}

// UnboundAtGTE applies the GTE predicate on the "unbound_at" field.
func UnboundAtGTE(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldUnboundAt, v))
}

// UnboundAtLT applies the LT predicate on the "unbound_at" field.
func UnboundAtLT(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldUnboundAt, v))
}

// UnboundAtLTE applies the LTE predicate on the "unbound_at" field.
func UnboundAtLTE(v time.Time) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldUnboundAt, v))
}

// UnboundAtIsNil applies the IsNil predicate on the "unbound_at" field.
func UnboundAtIsNil() predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIsNull(FieldUnboundAt))
}

// UnboundAtNotNil applies the NotNil predicate on the "unbound_at" field.
func UnboundAtNotNil() predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotNull(FieldUnboundAt))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContainsFold(FieldReason, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldOperator, vs...))
}

// OperatorGT applies the GT predicate on the "operator" field.
func OperatorGT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldOperator, v))
}

// OperatorGTE applies the GTE predicate on the "operator" field.
func OperatorGTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldOperator, v))
}

// OperatorLT applies the LT predicate on the "operator" field.
func OperatorLT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldOperator, v))
}

// OperatorLTE applies the LTE predicate on the "operator" field.
func OperatorLTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldOperator, v))
}

// OperatorContains applies the Contains predicate on the "operator" field.
func OperatorContains(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContains(FieldOperator, v))
}

// OperatorHasPrefix applies the HasPrefix predicate on the "operator" field.
func OperatorHasPrefix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasPrefix(FieldOperator, v))
}

// OperatorHasSuffix applies the HasSuffix predicate on the "operator" field.
func OperatorHasSuffix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasSuffix(FieldOperator, v))
}

// OperatorEqualFold applies the EqualFold predicate on the "operator" field.
func OperatorEqualFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEqualFold(FieldOperator, v))
}

// OperatorContainsFold applies the ContainsFold predicate on the "operator" field.
func OperatorContainsFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContainsFold(FieldOperator, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.FieldContainsFold(FieldNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeySubPoolBinding) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeySubPoolBinding) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeySubPoolBinding) predicate.APIKeySubPoolBinding {
	return predicate.APIKeySubPoolBinding(sql.NotPredicates(p))
}
